### ISSUE TITLE
Feature request; Limit no of versions of a KDBX file

### ISSUE THREAD

**Issue by rolandraijmakers** [KoenZomers/KeePassOneDriveSync#101]
During synchronisation of my KDBX files I noticed that the space consumed by each KDBX file on OneDrive for Business is retaining multiple versions of the KDBX files.

My main KDBX file is 800 Kb large, and OneDrive for Business is keeping up to 100 versions, so in my case that would be 80 Mb for 100 files. 

So my request for future version of KeePassOneDriveSync is to have limitation on the number of versions kept of the file.

I also found an article that describes that it is now standard to retain 100 versions of each files. 
https://regarding365.com/document-library-versioning-changes-coming-soon-for-onedrive-for-business-and-team-sites-in-78012862b32

I'm also going to look to a feature to reduce the number of versions within OneDrive for Business. In my opinion OneDrive should have a feature that a user can decide how many versions he want to store.

**Comment by KoenZomers** [comment]
You can configure the amount of versions you want to keep for all you files on OneDrive by going to /_layouts/viewlsts.aspx and going to the list settings for Documents. You cannot do this specifically for 1 file.

![image](https://user-images.githubusercontent.com/5940670/60720158-29c91e80-9f2a-11e9-93a8-f2e80190c4ad.png)

Would this be sufficient or are you really looking for a setting that would delete older versions of only your KeePass database files?

**Comment by rolandraijmakers** [comment]
Thank you, 

This is the setting i'm looking for. 
The only problem is I cant access /_layouts/viewlsts.aspx   
I'm going to contact my support engineer who has more authorization than I have.

I was in the impression that Microsoft has deleted this feature since september 2018. 
https://regarding365.com/document-library-versioning-changes-coming-soon-for-onedrive-for-business-and-team-sites-in-78012862b32

**Comment by KoenZomers** [comment]
That would be odd if you don't have access to it. By default every user is a site collection admin on their own OneDrive which means they will have full access to it. Changing this would bring the OneDrive in an unsupported state.

The change described in the article you link to was a different change. It regarded changing the default amount of versions to keep to accommodate things like the regular automatic saving of Office documents stored on a OneDrive. Lowering that setting would mean that you could maybe not go further back than one hour in time on an Office document you have actively worked on. So change this with care as it is for all your files on your entire OneDrive.

**Comment by rolandraijmakers** [comment]
I've found the setting, but not via the URL you posted.

OneDrive --> Back to classic view --> Library --> Library Settings --> Settings for Versions

The default setting is 500 versions. I changed this to 100 versions, which in my opinion is still too much.

So the minimum no of versions is set by Microsoft for OneDrive, an cannot be altered.
https://office365itpros.com/2018/08/16/spo-100-versions-minimum/

According to the article there was an escape for users to turn of versioning before september 2018.
As I am using KeeOneDrive now for 2 months I'm not able to change these settings.

Also I read that Microsoft doesn't calculate the space taken by versions, But thats is in my opinion not true. Every version is accounted for in the total amount of OneDrive space.

For now I'm going to monitor whether the versioning setting to 100 works. 

For me I also have to deal with some non-tech-savy colleges who will pump gigabytes of data to OneDrive. 

But anyway thank you for your responses.

**Comment by KoenZomers** [comment]
As far as I'm aware of the versions are indeed counted towards your quota. You do have 1 TB by default on OneDrive for Business, can have it raised for free to 5 TB by your admin and if you have a fair amount of licenses you can even extend it to unlimited storage, so it should not really be a problem. Also hope your people are not stashing gigabytes of files into KeePass databases :)

I'll close this one for now. If you still would need something to delimit the amount of historical items in OneDrive for Business, just reopen and let me know. I can probably fairly easily incorporate such functionality in the code, but I can't imagine there will be a lot of demand for such a feature to be honest.
