### ISSUE TITLE
The following plugin is incompatible with the current Keepass version

### ISSUE THREAD

**Issue by tomwignall** [KoenZomers/KeePassOneDriveSync#103]
I am getting the above error message. I have just updated to the latest version of One drive plugin. I have also unblocked the file.

**Comment by KoenZomers** [comment]
Sorry I uploaded a version in which a file was missing which was causing this error. I updated it five minutes later. I think you may have downloaded it before that. Just download it again under releases and try it again.

**Comment by tomwignall** [comment]
Working now thank you.
