### ISSUE TITLE
OneDrive's password is not saved

### ISSUE THREAD

**Issue by bastikus** [KoenZomers/KeePassOneDriveSync#104]
Hi, Koen!

Can plugin "KeePassOneDriveSync" remember my login and password from OneDrive Personal?
Currently I need every time input it when i run KeePass. I use Windows 10.

**Comment by KoenZomers** [comment]
Hi @bastikus. Yes it should. I have seen this behavior randomly for some people. Which option are you using to connect: Graph or OneDrive and where do you let it store your token: in the KeePass database or on your local machine?

**Comment by bastikus** [comment]
I use plugin from 2016 (or 2017) and when plfx file updated i replace it. Everything worked fine.
But problem happens about one month ago.
After your questions I deleted the configuration, then created it again, because i didn't remember what i did 2 or 3 years ago :) 
Chose options: "Microsoft Graph" and "Store the Refresh Token in the KeePass database itself".
And now plugin remember my login and password!!! Thank you very much for your help!

**Comment by KoenZomers** [comment]
Nice!
