### ISSUE TITLE
Version 2.0.7.1 doesn't work with Keepass 2.42.1

### ISSUE THREAD

**Issue by Sir-Launcelot** [KoenZomers/KeePassOneDriveSync#105]
![image](https://user-images.githubusercontent.com/6750561/60986599-d54ce700-a30d-11e9-9348-0a3fe8f98718.png)

**Comment by KoenZomers** [comment]
Try downloading 2.0.7.2 and see if that solves it for you

**Comment by CultUr** [comment]
I had the same issue and using version 2.0.7.2 solved my problem.

**Comment by KoenZomers** [comment]
Thanks for letting me know @CultUr. Several people already confirmed that in the re-released version it works well. I renamed the re-release to 2.0.7.1-2 to hopefully end the confusion.
