### ISSUE TITLE
Plugin won't load

### ISSUE THREAD

**Issue by IanIreland** [KoenZomers/KeePassOneDriveSync#107]
Hi - I upgraded the plugin but get an error message when I try to open Keepass; 
![image](https://user-images.githubusercontent.com/47241053/61130685-2b0cc500-a4af-11e9-9d67-9aca5c6af305.png)

**Comment by IanIreland** [comment]
OK - I found the re-released file - that loads!

**Comment by Hizan** [comment]
> OK - I found the re-released file - that loads!

I'm having this issue too and have tried re-downloading the plugin file but seem to keep getting the same error?

What did you do to resolve this?

**Comment by IanIreland** [comment]
Look here; https://github.com/KoenZomers/KeePassOneDriveSync/releases
I downloaded the patched file, put it in the plugins folder and it worked

**Comment by Hizan** [comment]
Ah-ha. Didn't catch that. Thanks a lot, works a treat!

**Comment by IanIreland** [comment]
:-)
