### ISSUE TITLE
"Pick an account" shows up on each open

### ISSUE THREAD

**Issue by pro-logic** [KoenZomers/KeePassOneDriveSync#108]
After upgrading my KeePassOneDriveSync (from 2.0.4 or .5 I think) to the latest .7 and .8 relaeses every time I open the a database I now get a "Authenticate to OneDrive" window that says:

"Pick an Account" and then it lists the two accounts I have on this PC one is "connected to windows" the other is "Signed in". 

I have to manually choose the account every single time. This didn't used to happen previously. 

Any ideas on how to fix this? Bit annoying, but other than that everything seems to work fine. 

![image](https://user-images.githubusercontent.com/552851/62014558-df178b00-b1e5-11e9-94d2-6cdffe54908d.png)

**Comment by KoenZomers** [comment]
Try removing the configuration for your sync under Tools \ KeePass OneDriveSync options and hit ctrl+s to set up the sync again. This typically fixes it.

**Comment by pro-logic** [comment]
Yep, manually deleting and re-creating the link worked.

Thanks.
