### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by BlueTarBeast** [KoenZomers/KeePassOneDriveSync#11]
I am unclear as to syntax of "Location" on OneDrive where the file should be kept.  I tried just MyFolder and \MyFolder, but I am getting this exception.
Kurt Schmidt

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at KoenZomersKeePassOneDriveSync.KeePassDatabase.<SyncDatabase>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KoenZomersKeePassOneDriveSync.KoenZomersKeePassOneDriveSyncExt.<MainWindowOnFileSaved>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.30.0.15916
    Win32 Version: 2.30.0.0
    CodeBase: file:///C:/Program%20Files/KeePass%20Password%20Safe%202/KeePass.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34251 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34270 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
KeeOtp
    Assembly Version: 1.3.1.0
    Win32 Version: 1.3.1
    CodeBase: file:///C:/Program%20Files/KeePass%20Password%20Safe%202/KeePlugini/KeeOpt-1.3.1-Full/KeeOtp.dll
----------------------------------------
KPDataSave
    Assembly Version: 0.0.4.0
    Win32 Version: 0.0.4.0
    CodeBase: file:///C:/Program%20Files/KeePass%20Password%20Safe%202/KeePlugini/KPDataSave/KPDataSave.dll
----------------------------------------
StrengthReport
    Assembly Version: 2.0.6.10301
    Win32 Version: 0.1.0.0
    CodeBase: file:///C:/Program%20Files/KeePass%20Password%20Safe%202/KeePlugini/PasswordStrengthReport/StrengthReport.dll
----------------------------------------
CertKeyProviderPlugin
    Assembly Version: 2.0.8.3
    Win32 Version: 2.0.8.3
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/J32VwfPGi33uFXtHNFY0/CertKeyProviderPlugin.dll
----------------------------------------
DataBaseBackup
    Assembly Version: 2.0.8.6
    Win32 Version: 2.0.8.6
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/kO3txUlZ2sBfmkEdw71p/DataBaseBackup.dll
----------------------------------------
DataBaseReorder
    Assembly Version: 2.0.8.0
    Win32 Version: 2.0.8.0
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/cmQFVSUzyRyWmsj24c0a/DataBaseReorder.dll
----------------------------------------
KeePassFaviconDownloader
    Assembly Version: 2.0.9.34607
    Win32 Version: 1.4.1.0
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/VPIN2E3JWATKcNKBOluf/KeePassFaviconDownloader.dll
----------------------------------------
GoogleSyncPlugin
    Assembly Version: 2.1.2.0
    Win32 Version: 2.1.2.0
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/4DE6DufKUPlICVkmRP6J/GoogleSyncPlugin.dll
----------------------------------------
IOProtocolExt
    Assembly Version: 1.8.0.0
    Win32 Version: 1.8.0.0
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/jqkKVAHaONfkjKafcDWY/IOProtocolExt.dll
----------------------------------------
ITanMaster
    Assembly Version: 2.28.0.39112
    Win32 Version: 2.28.0.2
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/LjjUFZJZa3Jvsq5MXmn9/ITanMaster.dll
----------------------------------------
KeeAutoExec
    Assembly Version: 1.6.0.34609
    Win32 Version: 1.6.0.0
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/cZNsyBlRF9UqACphyUrH/KeeAutoExec.dll
----------------------------------------
KoenZomersKeePassOneDriveSync
    Assembly Version: 1.3.3.1
    Win32 Version: 1.3.3.1
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/2a1MqffhqaUWTyWL0sCL/KoenZomersKeePassOneDriveSync.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.8.18111
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/2a1MqffhqaUWTyWL0sCL/Newtonsoft.Json.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
KeePassTrueCryptMount
    Assembly Version: 2.1.0.34610
    Win32 Version: 2.1.0.0
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/MJBrxVD1RWRVwaEibzgl/KeePassTrueCryptMount.dll
----------------------------------------
KPEnhancedListview
    Assembly Version: 2.1.0.34611
    Win32 Version: 0.9.1.0
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/tIz0hdXVq1B9iKx5xKxK/KPEnhancedListview.dll
----------------------------------------
pwm2keepass
    Assembly Version: 2.0.9.34611
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/FPOXkTXH3QdhU7BxWv2m/pwm2keepass.dll
----------------------------------------
PronouncePwGen
    Assembly Version: 1.0.3.34612
    Win32 Version: 1.0.3.0
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/1dUI4kt4CB9rQz4aKIOw/PronouncePwGen.dll
----------------------------------------
KeePassReadablePassphrase
    Assembly Version: 2.21.0.0
    Win32 Version: 0.11.0.0
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/MdJK3OExwYWBSh1FNuGb/KeePassReadablePassphrase.dll
----------------------------------------
TitleDisplay
    Assembly Version: 2.0.9.34613
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/784Ynan3UJgU35mGG6jb/TitleDisplay.dll
----------------------------------------
TrayTotpGT
    Assembly Version: 2.0.0.5
    Win32 Version: 2.0.0.5
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/v1mP4g5flqutbqEjZfDt/TrayTotpGT.dll
----------------------------------------
TwofishCipher
    Assembly Version: 2.0.9.34615
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/5BhnjyJELxldMI4leCYr/TwofishCipher.dll
----------------------------------------
WinKee
    Assembly Version: 2.28.0.39115
    Win32 Version: 2.28.0.1
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/JszluzTa1xAkk5bpIq7g/WinKee.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34252 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.30.0.15916
    Win32 Version: 2.30.0.15916
    CodeBase: file:///C:/Program%20Files/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL
----------------------------------------
OtpSharp
    Assembly Version: 1.0.4.0
    Win32 Version: 1.0.4
    CodeBase: file:///C:/Program%20Files/KeePass%20Password%20Safe%202/KeePlugini/KeeOpt-1.3.1-Full/OtpSharp.DLL
----------------------------------------
KoenZomers.OneDrive.Api
    Assembly Version: 1.3.1.0
    Win32 Version: 1.3.1.0
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/2a1MqffhqaUWTyWL0sCL/KoenZomers.OneDrive.Api.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Google.Apis.Authentication.OAuth2
    Assembly Version: 1.2.4696.27633
    Win32 Version: 1.2.4696.27633
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/4DE6DufKUPlICVkmRP6J/Google.Apis.Authentication.OAuth2.DLL
----------------------------------------
DotNetOpenAuth
    Assembly Version: 4.0.0.11165
    Win32 Version: 4.0.0.11165
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/4DE6DufKUPlICVkmRP6J/DotNetOpenAuth.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.2.4696.27637
    Win32 Version: 1.2.4696.27637
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/4DE6DufKUPlICVkmRP6J/Google.Apis.DLL
----------------------------------------
Google.Apis.Drive.v2
    Assembly Version: 1.2.4696.27611
    Win32 Version: 1.2.4696.27611
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/4DE6DufKUPlICVkmRP6J/Google.Apis.Drive.v2.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
Newtonsoft.Json.Net35
    Assembly Version: 4.0.2.0
    Win32 Version: 4.0.2.13801
    CodeBase: file:///C:/Users/Brahms/AppData/Local/KeePass/PluginCache/4DE6DufKUPlICVkmRP6J/Newtonsoft.Json.Net35.DLL
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/Windows/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34280 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.ServiceModel.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Web/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Web.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34268
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
RestSharpMerge_uc
    Assembly Version: 102.3.0.0
    Win32 Version: 0.0.4.0
    CodeBase: file:///C:/Program%20Files/KeePass%20Password%20Safe%202/KeePlugini/KPDataSave/KPDataSave.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by KoenZomers** [comment]
You need to include the filename on your OneDrive. I.e. if you want to store it in a folder MyFolder located in the root of your OneDrive and would like to name the file KeePass.kdbx, you would enter MyFolder\KeePass.kdbx

**Comment by BlueTarBeast** [comment]
Thanks!
