### ISSUE TITLE
Need to setup sync twice

### ISSUE THREAD

**Issue by keab** [KoenZomers/KeePassOneDriveSync#112]
I'm not sure if this is a real issue, but in any case the installation instructions would then need some updates
On my new computer I did 'Open from OneDrive', selected the kdbx file, then select a location on my C drive (which is not synched with OneDrive). The file is downloaded and opens up in KeePass. Everything fine so far.
But next time i opened the file on C:, I got the pop-up "This file/data base is not synched with OneDrive", And for the synch to work I again needed to select the OneDrive file and a synch is performed.
Thereafter it works fine just opening the local file.
Probably not the way it's thought out to work, is it?

**Comment by KoenZomers** [comment]
It isn't the expected behavior, but I have seen it happen in the past. As it's easily "fixed" by just logging on once again, I haven't looked into it further yet. Will have a look at it when I get a chance.

**Comment by keab** [comment]
It's not enough to log in, unfortunately. The request from the program is something like "where shall the file be placed", and you shall then select an existing file in OneDrive (unless you want to create a duplicate). That's a bit confusing and scary since you're not sure if you will delete or corrupt your online file. 
Until fixed, I suggest to add this to the installation instructions or troubleshooting or FAQ

**Comment by KoenZomers** [comment]
I can reproduce it. Let me see what is causing this behavior.

**Comment by KoenZomers** [comment]
Found what was causing it. It was a bug. It has been fixed in [version 2.0.9.0](https://github.com/KoenZomers/KeePassOneDriveSync/releases/tag/2.0.9.0). Thanks for reporting it @keab!
