### ISSUE TITLE
Setup Issue connecting to microsoftonline.com

### ISSUE THREAD

**Issue by sanga549** [KoenZomers/KeePassOneDriveSync#113]
Installed KeyOneDriveSync.plgx plugin. Opened KP, started to go through the OneDrive authentication but the popup says Can't reach this page, https://login.microsoftonline.com.  I can get to that URL page from a browser so I know the link works. Not sure why KP cannot reach it.
![Onedrive](https://user-images.githubusercontent.com/55607004/65364596-cf626480-dbe0-11e9-8e3d-aad537d8c3bf.png)
![msonline](https://user-images.githubusercontent.com/55607004/65364597-d38e8200-dbe0-11e9-9ca3-4968652c6e2d.png)

**Comment by KoenZomers** [comment]
This is not something my code has any influence on. Are you using a proxy by chance? Does logging in to your OneDrive site via Internet Explorer work? The webbrowser container used by my plugin is Internet Explorer, so test it explicitly with that browser. Try other network connections if you can. Try pinging login.microsoftonline.com. Or just simply try it at another moment as it could be a temporary glitch in a DNS, on the network or on the Microsoft side.

**Comment by sanga549** [comment]
I am not using a proxy. OneDrive does work in Internet Explorer though I have to go through 2FA to complete the login so maybe that's hosing up your plugin.

Looks like ICMP is turned off and DNS resolves to another name but as mentioned login.microsoftonline.com works fine in IE, Chrome and Firefox.

C:\>ping login.microsoftonline.com

Pinging www.tm.a.prd.aadg.akadns.net [40.126.3.34] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 40.126.3.34:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

**Comment by KoenZomers** [comment]
That it resolves to a different host is normal. Strange, not sure what can be done here. The MFA process should work fine, using that myself as well and hopefully most people these days :)

One last thing you could try is to run Fiddler while going through the login process. Perhaps that will reveal something.

**Comment by KoenZomers** [comment]
I have added a new authentication flow in [version 2.1.0.0](https://github.com/KoenZomers/KeePassOneDriveSync/releases/latest) which I have just released. That should resolve your issue. Use the top option "Any browser" on the "OneDrive" tab and follow the steps to authenticate.

**Comment by sanga549** [comment]
Hi,

Thanks for the update. I tried the new “Any Browser” option but it didn’t work for me.  First the Microsoft box opens saying “Communicating with the Microsoft Graph API…” then 2 seconds later the Unhandled exception is thrown.



The text below  the ++++++++ line is the from the Details page of the GUI. Hope that helps diagnostics.

Sorry, wish I had better news.

Regards,
Mike

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 40.126.0.74:443
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at KoenZomersKeePassOneDriveSync.OneDriveGraphDeviceLoginForm.GetMicrosoftGraphDeviceId()
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 40.126.0.74:443
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---<---

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.43.0.18739
    Win32 Version: 2.43.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe/KeePass.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
KoenZomersKeePassOneDriveSync
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.0
    CodeBase: file:///C:/Users/Mike/AppData/Local/KeePass/PluginCache/H1GbOR84qygrAJRqdmfe/KoenZomersKeePassOneDriveSync.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.1.19229
    CodeBase: file:///C:/Users/Mike/AppData/Local/KeePass/PluginCache/H1GbOR84qygrAJRqdmfe/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.43.0.18739
    Win32 Version: 2.43.0.18739
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe/KeePass.XmlSerializers.DLL
----------------------------------------
KoenZomers.OneDrive.Api
    Assembly Version: 2.3.0.3
    Win32 Version: 2.3.0.3
    CodeBase: file:///C:/Users/Mike/AppData/Local/KeePass/PluginCache/H1GbOR84qygrAJRqdmfe/KoenZomers.OneDrive.Api.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by KoenZomers** [comment]
Can you download the Microsoft tool PSPing from:
https://docs.microsoft.com/en-us/sysinternals/downloads/psping

Extract it to anywhere you'd like and run:
psping.exe login.microsoftonline.com:443

Please share the output of running this.

**Comment by sanga549** [comment]
Sure, here you go:

PsPing v2.10 - PsPing - ping, latency, bandwidth measurement utility
Copyright (C) 2012-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

TCP connect to 40.126.0.68:443:
5 iterations (warmup 1) ping test:
Connecting to 40.126.0.68:443 (warmup): from 10.44.11.6:64582: 47.68ms
Connecting to 40.126.0.68:443: from 10.44.11.6:64583: 29.34ms
Connecting to 40.126.0.68:443: from 10.44.11.6:64591: 48.36ms
Connecting to 40.126.0.68:443: from 10.44.11.6:64592: 34.04ms
Connecting to 40.126.0.68:443: from 10.44.11.6:64601: 28.22ms

TCP connect statistics for 40.126.0.68:443:
  Sent = 4, Received = 4, Lost = 0 (0% loss),
  Minimum = 28.22ms, Maximum = 48.36ms, Average = 34.99ms

**Comment by KoenZomers** [comment]
Just now noticed from your initial screenshot that you're still using an old version of the KeePass OneDriveSync plugin. Please upgrade to the latest version and use the "Any Browser" option from the "OneDrive" tab instead.

**Comment by sanga549** [comment]
Per the KP website I am using the current version.



It’s ok. I’ve made other arrangements to sync to OneDrive.

-Mike
