### ISSUE TITLE
BSOD with cldflt.sys and OneDrive 2019 Build 19.086.0502.0010

### ISSUE THREAD

**Issue by Dence07** [KoenZomers/KeePassOneDriveSync#115]
I recently updated my KeePassOneDriveSync to version 2.0.90 and began experiencing BSOD today whenever I open KeePass, login to KeePass, and close KeePass. This happened three times already starting today only. I suspect it has something to do with KeePassOneDriveSync since the memory dump and crash dumps from my laptop points to cldflt.sys as the culprit.

Here are the mini dumps and memory dump analysis from WhoCrashed app:

On Wed 10/16/2019 12:20:00 AM your computer crashed or a problem was reported
crash dump file: C:\WINDOWS\Minidump\101619-11937-01.dmp
This was probably caused by the following module: cldflt.sys (0xFFFFF8053B1DFBFE) 
Bugcheck code: 0x3B (0xC0000005, 0xFFFFF8053B1DFBFE, 0xFFFF84865BBB5500, 0x0)
Error: SYSTEM_SERVICE_EXCEPTION
file path: C:\WINDOWS\system32\drivers\cldflt.sys
product: Microsoft® Windows® Operating System
company: Microsoft Corporation
description: Cloud Files Mini Filter Driver
Bug check description: This indicates that an exception happened while executing a routine that transitions from non-privileged code to privileged code. 
This appears to be a typical software driver bug and is not likely to be caused by a hardware problem. 
The crash took place in a Microsoft module. Your system configuration may be incorrect. Possibly this problem is caused by another driver on your system that cannot be identified at this time. 

On Tue 10/15/2019 6:52:07 AM your computer crashed or a problem was reported
crash dump file: C:\WINDOWS\Minidump\101519-9187-01.dmp
This was probably caused by the following module: cldflt.sys (0xFFFFF8018F31FBFE) 
Bugcheck code: 0x3B (0xC0000005, 0xFFFFF8018F31FBFE, 0xFFFFCB8267095940, 0x0)
Error: SYSTEM_SERVICE_EXCEPTION
file path: C:\WINDOWS\system32\drivers\cldflt.sys
product: Microsoft® Windows® Operating System
company: Microsoft Corporation
description: Cloud Files Mini Filter Driver
Bug check description: This indicates that an exception happened while executing a routine that transitions from non-privileged code to privileged code. 
This appears to be a typical software driver bug and is not likely to be caused by a hardware problem. 
The crash took place in a Microsoft module. Your system configuration may be incorrect. Possibly this problem is caused by another driver on your system that cannot be identified at this time. 

On Tue 10/15/2019 6:08:15 AM your computer crashed or a problem was reported
crash dump file: C:\WINDOWS\Minidump\101519-10593-01.dmp
This was probably caused by the following module: cldflt.sys (0xFFFFF8002ADBFBFE) 
Bugcheck code: 0x3B (0xC0000005, 0xFFFFF8002ADBFBFE, 0xFFFF9B0AACBAD500, 0x0)
Error: SYSTEM_SERVICE_EXCEPTION
file path: C:\WINDOWS\system32\drivers\cldflt.sys
product: Microsoft® Windows® Operating System
company: Microsoft Corporation
description: Cloud Files Mini Filter Driver
Bug check description: This indicates that an exception happened while executing a routine that transitions from non-privileged code to privileged code. 
This appears to be a typical software driver bug and is not likely to be caused by a hardware problem. 
The crash took place in a Microsoft module. Your system configuration may be incorrect. Possibly this problem is caused by another driver on your system that cannot be identified at this time. 

On Wed 10/16/2019 12:20:00 AM your computer crashed or a problem was reported
crash dump file: C:\WINDOWS\MEMORY.DMP
This was probably caused by the following module: fltmgr.sys (FLTMGR!FltDecodeParameters+0xEA3) 
Bugcheck code: 0x3B (0xC0000005, 0xFFFFF8053B1DFBFE, 0xFFFF84865BBB5500, 0x0)
Error: SYSTEM_SERVICE_EXCEPTION
file path: C:\WINDOWS\system32\drivers\fltmgr.sys
product: Microsoft® Windows® Operating System
company: Microsoft Corporation
description: Microsoft Filesystem Filter Manager
Bug check description: This indicates that an exception happened while executing a routine that transitions from non-privileged code to privileged code. 
This appears to be a typical software driver bug and is not likely to be caused by a hardware problem. 
The crash took place in a file system driver. Since there is no other responsible driver detected, this could be pointing to a malfunctioning drive or corrupted disk. It's suggested that you run CHKDSK.

**Comment by KoenZomers** [comment]
I'm not using any custom drivers for the KeePassOneDriveSync. In the end it's just making basic HTTPS calls to the webservices of the Microsoft Graph or OneDrive. Not sure what would be using some kind of cloud driver. You could try force shutting down onedrive.exe using Task Manager on your machine which is the OneDrive sync client from Microsoft. Do that and see if you still get these crashes when working with KeePass. If not, the issue lies with that and I suggest filing your issue with Microsoft. You can easily do this by clicking on the blue or white OneDrive cloud icon in the system tray and clicking on Get Help in the context menu that appears. A support engineer will contact you to provide assistance.

**Comment by Dence07** [comment]
Thanks you. I will try your suggestion. I also upgraded the version of
OneDrive installed in my laptop today to see if it will solve the problem.

**Comment by Dence07** [comment]
- After upgrading OneDive client to build 19.152.0801.0009 (latest version as of October 16, 2019), I still get BSOD when opening KeePass and syncing the local DB using KeePassOneDriveSync.

- I tried closing OneDrive application and ending all processes related to KeePass but still experienced the BSOD when syncing the local KeePass database to SharePoint (after adding a new entry in my KeePass).

- I really doubt that this issue is specific only for KeePassOneDriveSync 2.0.9.0 since my issue with the BSOD stopped when I rolled back to the older KeePassOneDriveSync 2.0.8.0. I'm still crossing my fingers though, but for the last 10 minutes and after doing different tasks involving KeePass and syncing to SharePoint, I am still to experience another BSOD. This was not possible before while I was using version 2.0.9.0 since my laptop will immediately get the BSOD as soon as I open KeePass and let it sync automatically from SharePoint.

**Comment by Dence07** [comment]
Update after 16 hours:

- I'm still getting the BSOD. This is probably due to another Microsoft update that was recently applied to my laptop.

**Comment by KoenZomers** [comment]
Any more of these unlucky events? I had it happen to myself once on one of my devices only just like you describe. After that it didn't happen anymore. Not sure what it was, but it seems to no longer occur for myself and I haven't had anyone else report it.

**Comment by Dence07** [comment]
Unfortunately, it's still happening to me and my colleague from another country who is using the same Windows 10 Version 1903. We are both using the plugin and the BSOD happens whenever the plugin syncs with the SharePoint copy of our KeePass database. It does not happen to my colleagues who are using 1809, 1803, and other lower versions of Windows 10.

**Comment by KoenZomers** [comment]
Wicked. I'm on 1909 now and it doesn't seem to happen anymore. There's really nothing I can do different in my code as they're just plain HTTP calls in the end. I'm afraid it will be a matter of waiting for the next Windows 10 version to come out and jump in on that. If you're experiencing this issue on a corporate device, you may also consider filing a support case with Microsoft on it so someone can analyze the memory dumps to find out what's going on.

**Comment by Dence07** [comment]
There is an ongoing discussion regarding this in the official KeePass bugs page:

https://sourceforge.net/p/keepass/bugs/1891/?page=1

**Comment by KoenZomers** [comment]
Thanks for sharing @Dence07. So the issue may be with KeePass itself. Still strange that it seems that only a handful of people are having the issue, too.

**Comment by luisgepeto** [comment]
Hello
This seems to be a MS issue. Downgrading to Keepass 2.38 seems to solve the issue

**Comment by KoenZomers** [comment]
Thanks for sharing @luisgepeto

**Comment by KoenZomers** [comment]
Copying in from the KeePass bug report, it seems that installing this Microsoft Windows patch resolves this issue:
https://support.microsoft.com/en-us/help/4522355/windows-10-update-kb4522355

Closing this issue as it seems resolved by this.
