### ISSUE TITLE
Security implications

### ISSUE THREAD

**Issue by charsi** [KoenZomers/KeePassOneDriveSync#116]
Hi

Just trying to figure out the security implications of using this plugin. I know the code is open source and I can compile it myself so I shouldn't worry there. But to what extent is your server involved?  
Does it handle callbacks from Microsoft authentication during oAuth flow?  
Would a malicious actor be able to compromise a user's account if they gained access to your server?  

As a suggestion I'd recommend adding clear disclaimers if any of these are a valid concern. Thanks.

**Comment by KoenZomers** [comment]
Valid question and concern. There is no data that flows in any way to any service I host or own for this plugin. All communication goes directly between the KeePass client and the cloud provider where the data is hosted, such as Microsoft OneDrive for Business. The traffic between KeePass and Microsoft is encrypted through HTTPS encryption. The refresh token which could give access to the storage provider, such as OneDrive for Business, is stored to prevent having to authenticate over and over again on each synchronization. This token is stored either in the KeePass database, thus encrypted and secured in the same ways as everything else in your KeePass database is, or on your local file system in the user profile folder:

C:\Users\<username>\AppData\Roaming\KeePass

The token in this config file is encrypted using built-in Windows encryption and only can be decrypted if you are logged on to Windows with the same user as under which this data is stored.

Communication with the storage providers happens via my [OneDriveAPI](https://github.com/KoenZomers/OneDriveAPI) open source API, as you can see in the [package reference](https://github.com/KoenZomers/KeePassOneDriveSync/blob/master/KoenZomers.KeePass.OneDriveSync/packages.config). If you want to see exactly where it specifies which services to communicate with, see here:

- [OneDrive for Business](https://github.com/KoenZomers/OneDriveAPI/blob/master/Api/OneDriveForBusinessO365Api.cs)
- [OneDrive Consumer](https://github.com/KoenZomers/OneDriveAPI/blob/master/Api/OneDriveConsumerApi.cs)
- [Microsoft Graph API](https://github.com/KoenZomers/OneDriveAPI/blob/master/Api/OneDriveGraphApi.cs)

You will find the URLs of the services it communicates with at the top of each file. You can see that these are all Microsoft owned and managed services and all communicate through HTTPS.

I recommend you to read up on the oAuth flow which will show you that all communication will always go between the client and the oAuth server directly, without having any third parties in between:

https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth?view=odsp-graph-online

Let me know if you have further questions or concerns.

**Comment by KoenZomers** [comment]
I have added this same information to the FAQ, in case others may have the same question:
https://github.com/KoenZomers/KeePassOneDriveSync/blob/master/Faq.md#is-there-any-keepass-data-that-flows-through-any-of-your-environments

**Comment by KoenZomers** [comment]
Closing this issue as no further feedback has been received.

**Comment by charsi** [comment]
Thanks for the update Koen. Good to know server is not involved in authentication.
