### ISSUE TITLE
Automatically logs me in the wrong OneDrive account

### ISSUE THREAD

**Issue by YouGotHitByGunner** [KoenZomers/KeePassOneDriveSync#117]
Hey! I've learned about your plugin recently and wanted to give it a try.
When the Microsoft Graph window opens, it automatically logs me in the wrong account, more specifically, in my Office 365 student account. And it won't let me press the "Use another account" button, so I could try logging into my personal account.

**Comment by KoenZomers** [comment]
Hi there. Correct, many people are running into this. It is default behavior by Internet Explorer, which is used by the plugin and Windows 10 how it handles the automatic logon. I managed to find a way around this though by using a different authentication flow. I have added it in [version 2.1.0.0](https://github.com/KoenZomers/KeePassOneDriveSync/releases/latest) which I just released. Go ahead and give that a try. Choose the top option as shown below to use this new feature.

![image](https://user-images.githubusercontent.com/5940670/67664778-9bf5c100-f968-11e9-8590-39ceb777f2f9.png)

**Comment by YouGotHitByGunner** [comment]
It's working perfectly now, thank you!
Btw, is there a way you could take advantage of OneDrive's new feature?
https://onedrive.live.com/about/personal-vault/

**Comment by KoenZomers** [comment]
> Btw, is there a way you could take advantage of OneDrive's new feature?
> https://onedrive.live.com/about/personal-vault/

I'm keeping an eye on this one. At present there are no APIs yet to interact with this and it would require an interactive logon. When this changes, I may consider adding support for it.

Closing this issue now as the original problem has been resolved.
