### ISSUE TITLE
shared Onedrive for business DB is always overwritten when syncing

### ISSUE THREAD

**Issue by RonaldMeu** [KoenZomers/KeePassOneDriveSync#118]
Hi,

I'm trying to use the plugin to sync a shared database on Onedrive for business.
I'm using the following setup : 
Keepass(windows+plugin) <-sync-> Onedrive for business <-sync-> keepass2android 

The sync from Keepass (windows) is working ok to android with the shared database.
But from android to windows it is not because the plugin is overwriting the changes immediately when opening Keepass (windows).  It seems that the plugin is not detecting the changes in the database and always overwrite it.

Is it me doing something wrong ? 

How kan i setup this to work correctly ?

kind regards,
Ronald

**Comment by KoenZomers** [comment]
I just tested this and for me it seems to work fine. What I did:

1. I ensured KeePass was closed on my Windows device
2. I opened KeePass2Android on my phone
3. I made a modification to an existing entry, saved it and synced the database using the context menu at the top right
4. On my Windows PC I opened my KeePass database again, it synced and showed me the change I did on my Android phone

Does this match the steps you have taken?

**Comment by RonaldMeu** [comment]
Hello Koen ,  strange ...i took the same steps.
Did you use a key file ? or only a password ?

I use a key file for 2 factor authentication wich is more safe , because this file isn't shared on onedrive.
I used a older DB wich has lots of information in it.

kind regards,

Ronald

Ronald Meulendijks

Verzonden vanaf mijn smartphone.

________________________________

**Comment by KoenZomers** [comment]
Exactly the same scenario. KeePass database with password + key file which is not stored on OneDrive. Old large database established many many years ago. Are you sure you manually synced your KeePass database using the context menu at the top right (step 3 above)?

**Comment by RonaldMeu** [comment]
Hi , my android2keepass keeps on crashing when i want to edit and save something.
it throws an error about the MS Graph service. I contacted the developer about this and send him a log of this.  maybe the problem is not keepassOnedrive plugin.. and there is another problem causing this.

kind regards
Ronald

Ronald Meulendijks

Verzonden vanaf mijn smartphone.

________________________________

**Comment by KoenZomers** [comment]
What if you try it with a clean new KeePass database? Does it work then? Perhaps its some kind of corruption in the database itself?

**Comment by RonaldMeu** [comment]
Hi , i tried this.  with a new database it works.
Niw the trick ,  can i export en import my data into a new database without this issue.  I tried te imporr a backup.  but this copies the problem also

Ronald Meulendijks

Verzonden vanaf mijn smartphone.

________________________________

**Comment by KoenZomers** [comment]
I need to have a way to reproduce it before I can fix it. Can you try making a copy of your KeePass database and then deleting all entries in it leaving an empty database. See if it still occurs then. If so, please share that empty database with me so I can use that to reproduce it. If it doesn't happen anymore when you have deleted everything, perhaps try deleting a bunch of entries each time to try to narrow down the issue to the entry that causes the issue.

**Comment by RonaldMeu** [comment]
Hi,

I have made a new database.  after that the issue was resolved.

thank you for your reply.

kind regards,
Ronald

Ronald Meulendijks

Verzonden vanaf mijn smartphone.

________________________________

**Comment by KoenZomers** [comment]
Thanks for confirming @RonaldMeu. In that case I will proceed with closing this issue as well.
