### ISSUE TITLE
System.ArgumentNullException

### ISSUE THREAD

**Issue by olihya** [KoenZomers/KeePassOneDriveSync#119]
Hello, 

Thank you for your very useful app.

I use Keepass portable on a computer where i'm only user.

When i connect to onedrive, it tell me "Where to store the onedrive refresh token".
And i have this error.

Have you a solution?

Best wishes

Olivier

System.ArgumentNullException: La référence de chaîne n'est pas définie à une instance d'une chaîne.
Nom du paramètre : s
   à System.Text.Encoding.GetBytes(String s)
   à KoenZomersKeePassOneDriveSync.Utilities.Protect(String refreshToken)
   à KoenZomers.KeePass.OneDriveSync.Configuration.Save()
   à KoenZomersKeePassOneDriveSync.Utilities.<GetOneDriveApi>d__0.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à KoenZomersKeePassOneDriveSync.Providers.OneDriveProvider.<OpenFromOneDriveCloudProvider>d__1a.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à KoenZomersKeePassOneDriveSync.KeePassDatabase.<OpenDatabaseFromCloudService>d__2.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à KoenZomersKeePassOneDriveSync.KoenZomersKeePassOneDriveSyncExt.<MenuFileOpenFromOneDriveOnClick>d__7.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Assemblys chargés **************
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4018.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Version de l'assembly : 2.43.0.18739
    Version Win32 : 2.43.0.0
    CodeBase : file:///F:/KeePass/KeePass.exe
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3928.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3761.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3761.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4018.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3761.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3761.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
KoenZomersKeePassOneDriveSync
    Version de l'assembly : 2.0.8.0
    Version Win32 : 2.0.8.0
    CodeBase : file:///C:/Users/opuygranier/AppData/Local/KeePass/PluginCache/nsNPVy2T2zZoQL6mRa10/KoenZomersKeePassOneDriveSync.dll
----------------------------------------
Newtonsoft.Json
    Version de l'assembly : 8.0.0.0
    Version Win32 : 8.0.1.19229
    CodeBase : file:///C:/Users/opuygranier/AppData/Local/KeePass/PluginCache/nsNPVy2T2zZoQL6mRa10/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3761.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3928.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3761.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3761.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Security
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3761.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
KeePassRPC
    Version de l'assembly : 2.0.34.17563
    Version Win32 : 1.9.0.0
    CodeBase : file:///C:/Users/opuygranier/AppData/Local/KeePass/PluginCache/AxDYZg10g6dsxjxACSs1/KeePassRPC.dll
----------------------------------------
Fleck2
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/opuygranier/AppData/Local/KeePass/PluginCache/AxDYZg10g6dsxjxACSs1/Fleck2.DLL
----------------------------------------
DomainPublicSuffix
    Version de l'assembly : 2.0.1.0
    Version Win32 : 2.0.1.0
    CodeBase : file:///C:/Users/opuygranier/AppData/Local/KeePass/PluginCache/AxDYZg10g6dsxjxACSs1/DomainPublicSuffix.DLL
----------------------------------------
Jayrock
    Version de l'assembly : 0.9.12915.0
    Version Win32 : 0.9.11214.1056
    CodeBase : file:///C:/Users/opuygranier/AppData/Local/KeePass/PluginCache/AxDYZg10g6dsxjxACSs1/Jayrock.DLL
----------------------------------------
KeePass.XmlSerializers
    Version de l'assembly : 2.43.0.18739
    Version Win32 : 2.43.0.18739
    CodeBase : file:///F:/KeePass/KeePass.XmlSerializers.DLL
----------------------------------------
Jayrock.Json
    Version de l'assembly : 0.9.12915.0
    Version Win32 : 0.9.13422.2206
    CodeBase : file:///C:/Users/opuygranier/AppData/Local/KeePass/PluginCache/AxDYZg10g6dsxjxACSs1/Jayrock.Json.DLL
----------------------------------------
Microsoft.GeneratedCode
    Version de l'assembly : 1.0.0.0
    Version Win32 : 4.8.3761.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
KoenZomers.OneDrive.Api
    Version de l'assembly : 2.3.0.3
    Version Win32 : 2.3.0.3
    CodeBase : file:///C:/Users/opuygranier/AppData/Local/KeePass/PluginCache/nsNPVy2T2zZoQL6mRa10/KoenZomers.OneDrive.Api.DLL
----------------------------------------
mscorlib.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3761.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Microsoft.mshtml
    Version de l'assembly : 7.0.3300.0
    Version Win32 : 7.0.3300.0
    CodeBase : file:///C:/Windows/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------
System.Web
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3928.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Net.Http
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3761.0 built by: NET48REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------

************** Débogage JIT **************
Pour activer le débogage juste-à-temps (JIT), le fichier de configuration pour cette
application ou cet ordinateur (machine.config) doit avoir la valeur
jitDebugging définie dans la section system.windows.forms.
L'application doit également être compilée avec le débogage
activé.

Par exemple :

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

**Comment by KoenZomers** [comment]
Which option did you choose at the question where to store the token? Inside the KeePass database or on your file system? Have you tried both options? Do both result in this error? What Windows version are you on?

**Comment by olihya** [comment]
Hi Koen😃Thank you for your answer and also for what you do for the community.I have try the two options.Both result in this error.Keypass is the last portable version on a USB key. I use the OneDrive plugin.And I have try to use it on a Windows 7 as a user without administration rights.Wish you the bestSee you laterOlivierLe 11 nov. 2019 09:31, Koen Zomers <notifications@github.com> a écrit :Which option did you choose at the question where to store the token? Inside the KeePass database or on your file system? Have you tried both options? Do both result in this error? What Windows version are you on?

**Comment by KoenZomers** [comment]
Thanks for providing the additional information. I will need to find some time to try to reproduce it under these specific conditions. As I don't have a Windows 7 machine anymore, it may take quite a bit of time before I can get to this.

**Comment by olihya** [comment]
Hi Koen,
Thank you for your answer.
Ok, i wish you good luck and have a good day

**Comment by KoenZomers** [comment]
Sorry, still didn't get around to set up a test rig for this yet. And giving it another thought as Windows 7 has now run out of support anyway, I don't want to invest time in it anymore. Therefore going to close this issue. If the same problem exists on Windows 10, I'll be happy to look into it.
