### ISSUE TITLE
Use a file chooser for setting up the 

### ISSUE THREAD

**Issue by tobiasschuerg** [KoenZomers/KeePassOneDriveSync#12]
Or at least check if the path is valid.

---

It took me three times to set it up correctly
1. wrong path -> npe
2. just the pass without filename -> npe
3. it finally worked

**Comment by tobiasschuerg** [comment]
Just saw that #8 and #11 are also based on this issue.

**Comment by KoenZomers** [comment]
Thanks for your feedback! Yep, adding a file picker is on my todo list :)
