### ISSUE TITLE
Not able to set up sync with v2.1.0.0

### ISSUE THREAD

**Issue by Sir-Launcelot** [KoenZomers/KeePassOneDriveSync#121]
I get this error with either graph option, "Failed to sync database X: String reference not set to an instance of a String.  Parameter name: s"

I went back to 2.0.9.0, and it is working again.

When I was on 2.1.0.0, I tried deleting the stored sync information, but the problem existed.

**Comment by KoenZomers** [comment]
Thanks for reporting this. I will need more information to be able to reproduce this. Could you paste the full stack trace you will see in the error dialog here? Or do you get this error in the KeePass status bar at the bottom?

When does this error show? Exactly after doing what? Just clicking on Graph API already or later on after authenticating?

**Comment by KoenZomers** [comment]
Closing as no further feedback received
