### ISSUE TITLE
Exception when logging into OneDrive with MSGraph

### ISSUE THREAD

**Issue by erythana** [KoenZomers/KeePassOneDriveSync#126]
Hello,

the plugin seems to throw an exception when doing the following, only happened once though on my initial setup of KeePass2:
"Open from OneDrive"
"Microsoft Graph"
and then immediately click on the Code (or anywhere in this area).

This doesn't seem to occur anymore/can't reproduce...

**Comment by KoenZomers** [comment]
Thanks for letting me know @erythana. I also don't seem to be able to reproduce it and haven't heard anyone else report this yet. I'm therefore closing it for now. If you run into it again and know how to reproduce it, I'll gladly hear about it.
