### ISSUE TITLE
Request: Pass device code into browser link

### ISSUE THREAD

**Issue by jpdicicco** [KoenZomers/KeePassOneDriveSync#127]
It appears from [this link](https://social.msdn.microsoft.com/Forums/expression/en-US/6a7b7c48-b028-4761-8cb8-622e5c0ffa14/azure-device-authentication-link-with-code-already-embedded?forum=azureapimgmt) that the device code can be passed in a POST action.  This would remove the need to copy and paste the value and streamline the login process.

**Comment by KoenZomers** [comment]
Would be nice to take away the step to copy/paste the device id indeed. However the initial issue that I solved by offering this option is that internet explorer automatically logs on using credentials stored in Windows. To make a HTTP POST, I would need to take over the entire authentication process or use the internet explorer container again, which is something I don't want to do as 1) it would bring lots of complexity if two factor authentication would be used and 2) something as sensitive as credentials, I don't want to be flowing through my code, but want to keep at the authentication provider, as the models describe. If an option would exist to pass on the code in the URL, thus through a GET, I will definitely add it.

Thanks for the suggestion though!
