### ISSUE TITLE
KeePassOneDriveSync Tekenreeksverwijzing is niet voor een exemplaar van een string ingesteld Parameternaam: s

### ISSUE THREAD

**Issue by rolandraijmakers** [KoenZomers/KeePassOneDriveSync#128]
As a followup tot #121 https://github.com/KoenZomers/KeePassOneDriveSync/issues/121
"Failed to sync database X: String reference not set to an instance of a String. Parameter name: s"

I get the same kind of error message with KeePassOneDriveSync 

What i've found is one record in the Sync options is blank, and cannot be disabled. 
As soon as I delete this one blank line I get this errormessage. 

![2020-02-26 14_05_53-KeePassOneDriveSync Options - Reference to Non existing database](https://user-images.githubusercontent.com/46449678/75349756-ab98fe00-58a5-11ea-845b-b5127b531f70.png)

![2020-02-26 14_26_09-__bolacc nl_afdelingen__Afdel _Bol Accountants kdbx - KeePass](https://user-images.githubusercontent.com/46449678/75349796-b8b5ed00-58a5-11ea-9155-d9ed0b216cce.png)

![2020-02-26 14_27_42-__bolacc nl_afdelingen__Afdel _Bol Accountants kdbx - KeePass](https://user-images.githubusercontent.com/46449678/75349849-ce2b1700-58a5-11ea-8cff-648262345ae7.png)
[KeePassOneDriveSync - Error Message .txt](https://github.com/KoenZomers/KeePassOneDriveSync/files/4255993/KeePassOneDriveSync.-.Error.Message.txt)

**Comment by rolandraijmakers** [comment]
My KeePass Version is 2.44
My Koen.Zomers.KeePass.OneDriveSync is  2.1.1.1.

**Comment by KoenZomers** [comment]
Thanks for providing this detailed information @rolandraijmakers! Any idea what could have lead to the empty entry in the first place?

**Comment by KoenZomers** [comment]
Should be fixed in [version 2.1.1.2](https://github.com/KoenZomers/KeePassOneDriveSync/releases/tag/2.1.1.2)

**Comment by rolandraijmakers** [comment]
> Thanks for providing this detailed information @rolandraijmakers! Any idea what could have lead to the empty entry in the first place?

Hello Koen, I've got no idea why the empty entry got there. 
- We were working with on older version of KeePassOneDriveSync, and then upgraded to 2.1.1.1. So the config was made with an older version. 
- We've implemented Microsoft Conditional Access in januari 2020 where access to MSGraph authentiction is granted if the device id is known in microsoft intune.
- In Google Chrome we installed the microsoft extension for Chrome "Windows 10 accounts" Which passes through the device id from our PC to the microsoft Graph authentication.
- Where experiencing the prolblems mainly on our Microsoft RDS Servers where KeePass in installed in a shared environment. 

- I worked arround it by deleting the full section KeeOneDrive in the KeePass.
- I'm going to install 2.1.1.2. on my local PC and on let our external hosting party update our RDS Servers.

**Comment by KoenZomers** [comment]
Thanks for the extensive elaboration @rolandraijmakers. Especially coming from an older version, the encryption of the refresh tokens in the KeePass config file has changed and is known to not always be upgraded correctly. Simply deleting the config entry and hitting CTRL+S to set it up again fixes it. The updated KeePass plugin should allow you to delete the corrupted entries again and set it up again.

I believe with that, this issue can be marked as resolved. Feel free to reopen if you're still running into problems.
