### ISSUE TITLE
Issue with 2.44 will not load

### ISSUE THREAD

**Issue by AlexSamad** [KoenZomers/KeePassOneDriveSync#129]
![image](https://user-images.githubusercontent.com/5509219/79704823-95804a80-82f6-11ea-8c32-8bae2ffedafb.png)

**Comment by AlexSamad** [comment]
Sorry couldn't copy and paste the test . I downloaded the latest version

**Comment by AlexSamad** [comment]
So i deleted the tokens out of the config file and that seems to have fixed it.

maybe a try / catch to pop up -- delete / ignore stored tokens ?

**Comment by KoenZomers** [comment]
Did you happen to upgrade from a version before version 2.0.6.0 when you ran into this issue?

**Comment by KoenZomers** [comment]
Closing issue as no further feedback received
