### ISSUE TITLE
Microsoft MFA & Software Password

### ISSUE THREAD

**Issue by florillard** [KoenZomers/KeePassOneDriveSync#130]
Hi, since few version (actually in 2.1.1.2) I had to validate with my smartphone each time I open keepass (2.44). It is because my MFA Settings on my mircosoft account.

I would like to use a software password to not need to have my smartphone each time.

Software password seems not recognize by your plugin, because I have "Password wrong" message and I have to use Ms authentificator.

Do I something wrong ?

cheers

François

**Comment by KoenZomers** [comment]
That's odd. Nothing has changed in the code in recent versions that could cause anything like this. What technically happens is that you log on to Microsoft and once successful, it returns the plugin a so called refresh token. With a refresh token, access can be gained to the OneDrive without needing any MFA. If you are asked to authenticate again, it means the refresh token has invalidated and the plugin was unsuccesful in retrieving a new access token with it. This can happen in several situations, such as you changing your password, in case of using a School or Work account hosted in an Active Directory or the administrator having configured that tokens should only be short lived. 

Can you elaborate a bit more on a "software password"? Perhaps this is an authentication method which deals with its tokens different on the background and is meant to give out only short lived refresh tokens or no refresh tokens at all but just an access token.

**Comment by florillard** [comment]
Hi, in microsoft account, with MFA you can use "apps password" see [here](https://support.microsoft.com/en-us/help/12409/microsoft-account-app-passwords-and-two-step-verification).

what do you need I test ?

**Comment by KoenZomers** [comment]
Ah, these app passwords are indeed not supported for any kind of modern authentication, such as oAuth, which is what my plugin is using. It's more of a legacy type of authentication for old platforms that never got upgraded to support modern authentication, such as an Xbox 360.

Did you use the Microsoft Graph (Any Browser) option to authenticate?

![image](https://user-images.githubusercontent.com/5940670/80302413-30bb6900-87aa-11ea-8d67-faba1cf10825.png)

Once you have the sync set up, if you go to the OneDrive sync configuration via Tools -> OneDriveSync Options -> Double click or tap on your configuration entry, is there a value in the API Refresh Token field? Do **not** share this value here, just let me know if there is something in this field.

![image](https://user-images.githubusercontent.com/5940670/80302458-7bd57c00-87aa-11ea-9134-bbcf072761ae.png)

**Comment by florillard** [comment]
my CloudStorage type is OneDriveConsummer et my API Refresh Token in empty.
I will try to change my cloud Storage Type and I come back.

**Comment by florillard** [comment]
Gotcha ! I don't know but I dont remember to see the Ms Graph Options before. maybe my configuration was very old... now it working ! i have my API refresh token.
everything fine !! thanks !
