### ISSUE TITLE
[BUG] OneDrive Connection is lost at every restart

### ISSUE THREAD

**Issue by Olli2k** [KoenZomers/KeePassOneDriveSync#133]
**Describe the bug**
I needed to change my OneDrive password. After this (I don't know if this is connected with the passwordchange) KeePass was not able to sync with one drive. Due to I was not able to change any of the OneDrive Account options I deleted the OneDrive setup and restarted it. As expected I was asked to setup connection again. After this sync was successful. Fine.. well not really, I have to setup connection to OneDrive now every morning. It seems not to be saved and status says "never synced".

**To Reproduce**
I have no idea.

**Expected behavior**
I have no idea

**Screenshots**
![hc_1153](https://user-images.githubusercontent.com/22831306/84236607-2eae2f00-aaf8-11ea-9597-9a466b9d8a21.jpg)

**Versions (please complete the following information):**
- KeePass [e.g. 2.45]: 2.45
- KeePass OneDriveSync Plugin [e.g. 2.1.1.2]: 2.1.2.1

**Authentication method**
- [x] Microsoft Graph (any browser)
- [ ] Microsoft Graph (built in browser)
- [ ] OneDrive
- [ ] OneDrive for Business
- [ ] SharePoint 2013/2016/2019

**KeePass database synced with**
- [ ] OneDrive for Business
- [x] OneDrive Personal

**Comment by Olli2k** [comment]
Additional Info: I can't auth via internal browser, because I have 2 OneDrive accounts an this computer (personal & business) so internal browser selects always the business account, which is the wrong one.

**Comment by KoenZomers** [comment]
Interesting situation. If you change your account password, it will invalidate any outstanding oAuth tokens, which is what the plugin uses as well. So it's normal that when doing so, the plugin will ask for your credentials again next time it tries to sync.

Not sure why setting it up again fails. You will have to use the Any Browser authentication method to cover your scenario.

What you could try is to close KeePass and manually remove the configuration of this plugin by going to:

`C:\Users\kueppero\AppData\Roaming\KeePass`

And once there, opening the KeePass.config.xml file in notepad. Scroll down to the bottom of the file where you should see a section similar to:

![image](https://user-images.githubusercontent.com/5940670/84586264-32072a80-ae18-11ea-981f-aa2260cc2668.png)

Delete the \<Item\>...\</Item\> section which has the \<Key\>KeeOneDrive\</Key\>. Restart KeePass and try to set up the sync again.

Let me know if this yields better results.

**Comment by Olli2k** [comment]
Today after reboot configuration was stil there. So problem seems to be solved without any of the steps you advised. At least I hope so.
