### ISSUE TITLE
Not on Linux Mint 20 (Cinnamon)

### ISSUE THREAD

**Issue by HTroost** [KoenZomers/KeePassOneDriveSync#136]
Thanks for sharing @J-O-P! I've added a reference to your information at the [system requirements page](https://github.com/KoenZomers/KeePassOneDriveSync/wiki/System-Requirements).

Tried it on Linux Mint 20 (Cinnamon) - after installing Mono Complete - but does not work: the "Authenticate to Onedrive" dialog box, after pressing "Open in browser" returns (after ~30 seconds) a fatal error "cannot access a disposed object. Object name: KeePass.UI.CustomListViewEx". I collected the bug report from the clibboard in a text file which I can provide you with as you need it.
Remarkable: the Tools-->Onedrivesync Options show  Storage provider: MicrosoftGraph but on every open of the database KeePass prompts for starting the sync (Yes, Not now, never).
Hope this comment also helps a bit.

Kind regards, Hans Troost (NL)

**Comment by KoenZomers** [comment]
So you have used the "any browser" option and did see a code being generated, correct? What if you then manually open a web browser and navigate to https://microsoft.com/devicelogin, enter the code shown in KeePass and logon. How far do you get if you do that?

**Comment by HTroost** [comment]
Thanks for replying: just what I did: manually typed over the link .../devicelogin and the code shown on the “Authentication for onedrive” dialog. And yes: received MS’s confirmation email as well.
Nevertheless opening the database keeps me prompting for the sync.
Hans

**Comment by KoenZomers** [comment]
Must be something with the path then where it doesn't work well on Linux. If you're in the Tools -> OneDriveSync Options and check the path under _Local Path_ does that make any sense and is that where the database resides? Does the database reside in a path under the KeePass plugin or totally separate from it? Can you try placing it in the same folder as from where you run KeePass and see if that makes any difference?

**Comment by HTroost** [comment]
Thanks again Koen,

TChecked and tested - partly - your last suggestion.
In the Onedrive Sync Configuratio the path was correct but moved the db to /home/hans/ (part of your suggestion). Not possible to store it with the keepass2 program folder (/urs/lib/keepass2 with has root-only privs on linux).
But as said: tried it again with nearly the same result: same error and keeps prompting me, but: it added an extra entry in the "sync option pointint to the changed path, but with another provider (OndeDrive Concumer in stead of MicrosoftGraph). 
My thoughts: probably it is not Mint 20 OS causing this: Mint 20 is based on Ubuntu 20 which is based on Debian 10, which is the OS J-O-P used successfully. Possibly it is just the Cinnamond-desktop that causes the problem.

I attach the error messages and full error report to this post.

(BTW I posted mainly for your information: I can live without synced Keepass on Mint - I have other devices I use Keepass on. I just tries it for convenience.)
![2020-07-04 14-23-55 OneDrive Sync Configuration](https://user-images.githubusercontent.com/52462601/86512511-37e2a100-be03-11ea-9e46-d13794c7eb4c.png)
![2020-07-03 20-15-55 Error](https://user-images.githubusercontent.com/52462601/86512514-3c0ebe80-be03-11ea-8d2a-171761237076.png)
[KeepassOnedrive error.txt](https://github.com/KoenZomers/KeePassOneDriveSync/files/4872830/KeepassOnedrive.error.txt)

**Comment by J-O-P** [comment]
Strange. Probably I cant help here. For me (on Ubuntu 20.04) the synchronization works. 

![Screenshotkp1](https://user-images.githubusercontent.com/51044857/86514756-50a78280-be14-11ea-9227-aa11076ee1af.png)
![Screenshotkp2](https://user-images.githubusercontent.com/51044857/86514758-54d3a000-be14-11ea-9757-04bdce08c89e.png)

However KeePass seems to have a problem to open weblinks in a browser window. For example clicking one of the links in the KeePass Help - About KeePass Dialog results in an error ("Cannot find the specified file").  However using the "URL - open in Browser" function in a DB entry does work.

Also during the setup of  KeePassOneDriveSync with the any browser option I could not click to open the browser window, but had to navigate to  https://microsoft.com/devicelogin  manually and enter the code. (This however did work on Debian 10.4 as far as I remember). But since then the sync is working for me.

**Comment by HTroost** [comment]
Took me some time and other attempts (buth Ubuntu alongside Mint, and with a Mint VM (VirtualBox on W10-PC) as well, 
and I seem to have figured it out now: it seems to be a matter of timing: I always was to slow or intentionally waited to long. My last - and now successful -  attempt was: opening microsoft.com/devicelogin in firefox, starting KeePass, quickly copy the code from the dialogbox and finalize the verification. Then the dialogbox just closes after MS's processing (no error messages or crashes) and it works!

Thanks  both of you for your replies and willingness to help.
And is is a nice plugin Koen for the purpose I need it: very happy with it now!
Best regards, Hans Troost
