### ISSUE TITLE
[BUG] Failed To Upload

### ISSUE THREAD

**Issue by bl-sol** [KoenZomers/KeePassOneDriveSync#137]
**Describe the bug**
I want to share a KeePass database with my IT Team with SharePoint (previously was on webdav).
I set up all the SharePoint with the Register App, everything is good. When I try to save and upload my database (7mo), it fails with this error : Failed to upload the KeePass database <Name of my database>.
On the configuration everything is ready, and the credentials are good (Successful test connection). If I upload my database before, I cannot see it when browsing.

**Screenshots**
![image](https://user-images.githubusercontent.com/68240276/87325410-b640f080-c531-11ea-8536-70a26d8b4d7b.png)

**Versions (please complete the following information):**
- KeePass : 2.45
- KeePass OneDriveSync Plugin : 2.1.2.1

**Authentication method**
- [ ] Microsoft Graph (any browser)
- [ ] Microsoft Graph (built in browser)
- [ ] OneDrive
- [ ] OneDrive for Business
- [X] SharePoint Online

**KeePass database synced with**
- [ ] OneDrive for Business
- [ ] OneDrive Personal
- [X] SharePoint Online

**Comment by bl-sol** [comment]
Hello, any news about my issue ? : ) 

Regards

**Comment by KoenZomers** [comment]
Have you followed the exact steps listed on: https://github.com/KoenZomers/KeePassOneDriveSync/wiki/Configuration-options#sharepoint-2013-2016-2019-and-sharepoint-online-support ?

If you set up the sync and enter your SharePoint site URL, client id and client secret, please be sure to only include the URL to the site collection, not the entire url to the document library. Does the document library file picker show up after entering this information?

**Comment by KoenZomers** [comment]
Closing as no further feedback received
