### ISSUE TITLE
[FEATURE REQUEST] use 2 different onedrive (personal and business)

### ISSUE THREAD

**Issue by albgen** [KoenZomers/KeePassOneDriveSync#139]
**Is your feature request related to a problem? Please describe.**
i have two files. One on my personal onedrive which contains personal password and the other in onedrive business in which are contained the passwords used in the company

**Describe the solution you'd like**
be possible to list all possible configurations on the plugin

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by KoenZomers** [comment]
So if I understand you correctly, you want your personal KeePass database to be synced to your personal OneDrive and the one from your work to your OneDrive for Business? This is perfectly possible today. Using it myself that way. Just set up a sync for both of them to where they need to go.

**Comment by albgen** [comment]
yes, exactly but don't know how to set it up. Currently i have configured only the one for onedrive business.

**Comment by KoenZomers** [comment]
Just open your personal KeePass database in KeePass. As soon as you save it (hit ctrl+s) it will prompt you and ask you if you want to sync that database. Go through the steps to log on to your Personal OneDrive and store it there.

**Comment by albgen** [comment]
so, i have to manually download it from my personal onedrive and save it?

**Comment by KoenZomers** [comment]
That or in KeePass use File > Open > Open from OneDrive to automatically download and set up the sync

**Comment by albgen** [comment]
doing "File > Open > Open from OneDrive to automatically download and set up the sync" does not work because it is already logged in with the onedrive business.

**Comment by KoenZomers** [comment]
Use the Any Browser option and open it in an in private browser session and it's impossible that it will log you on automatically

![image](https://user-images.githubusercontent.com/5940670/94317675-13700e00-ff87-11ea-9a30-87fe8bbc3243.png)

**Comment by albgen** [comment]
thanks it worked.

**Comment by KoenZomers** [comment]
Excellent, enjoy.
