### ISSUE TITLE
Synchronization fails if current database is changed to another one

### ISSUE THREAD

**Issue by mushak** [KoenZomers/KeePassOneDriveSync#14]
I keep multiple databases open. Each uses different master key and passphrase. Some are synchronized with OneDrive, some are not. If I save a database configured to sync, but will switch tabs before KeePassOneDriveSync actually starts its work, the process will fail with 'The composite key is invalid' error.

**Comment by KoenZomers** [comment]
There's unfortunately very little I can do about this. I don't have control over the KeePass UI and the API prohibits me to interact with a database that is not currently the selected one. So please keep yourself from switching while a sync is running.
