### ISSUE TITLE
Open from OneDrive Business (Graph) fails

### ISSUE THREAD

**Issue by ProfDrYoMan** [KoenZomers/KeePassOneDriveSync#140]
**Describe the bug**
It did work before. Now it fails, after removing a link (because I wanted to move the kdbx file).
Open from OneDrive Business (Graph)

**To Reproduce**
1. Open from OneDrive
2. Business (Graph)
3. Window with key pops up
4. Wait 30 sec and get this error message: "Unexpected error: AADSTS70000: The provided value for the input parameter 'device_code' is not valid.
5. Opening in browser and authenticating after pasting the key does not work. Window stays.

**Expected behavior**
No such error and the chance to open a kdbx.

**Screenshots**
![image](https://user-images.githubusercontent.com/510353/98908967-767b1d00-24c1-11eb-84c4-4f10ecc5a61c.png)

**Versions (please complete the following information):**
- KeePass: 2.46
- KeePass OneDriveSync Plugin: 2.1.2.1

**Authentication method**
- [x] Microsoft Graph (any browser)
- [ ] Microsoft Graph (built in browser)
- [ ] OneDrive
- [x] OneDrive for Business
- [ ] SharePoint 2013/2016/2019

**KeePass database synced with**
- [x] OneDrive for Business
- [ ] OneDrive Personal

**Comment by KoenZomers** [comment]
I ran into this myself yesterday. Today however I cannot reproduce it anymore. Makes me think it was a glitch on the Microsoft side. Can you try again yourself and share if it works again for you as well?

**Comment by ProfDrYoMan** [comment]
Cannot reproduce. Works now, flawless.

=> Glitch
