### ISSUE TITLE
[BUG] tab shared with me is empty

### ISSUE THREAD

**Issue by scribepl** [KoenZomers/KeePassOneDriveSync#141]
**Describe the bug**
when im trying to open database file shared for me im go to: Tab "shared with me is empty", but its nothing there? im see only files from my 1drv (linking with acoount is working)

![image](https://user-images.githubusercontent.com/7255237/98968176-a3552180-250d-11eb-9253-b508f11e4a2e.png)

![image](https://user-images.githubusercontent.com/7255237/98968222-aea84d00-250d-11eb-8793-4142c6e8b305.png)

when im login to 1drv with webrowser i see all my folders - in plugin i'm see nothing? 
![image](https://user-images.githubusercontent.com/7255237/98968679-44dc7300-250e-11eb-9bea-d0ba22a16c8b.png)

**To Reproduce**
try to open shared for you files from your 1drv

**Versions (please complete the following information):**
- KeePass 2.46:
- KeePass OneDriveSync Plugin 2.1.2.1:

**Authentication method**
- [ ] Microsoft Graph (any browser)
- [ ] Microsoft Graph (built in browser)
- [ ] OneDrive
- [ X] OneDrive for Business
- [ ] SharePoint 2013/2016/2019

**KeePass database synced with**
- [X ] OneDrive for Business
- [ ] OneDrive Personal

**Comment by KoenZomers** [comment]
Thanks for sharing the screenshots. Looks like you're connecting with a OneDrive for Business site. For me seeing the shared items on a OneDrive for Business account seems to work, so there's something particular that's keeping you from seeing it. Can you try the following:

1. Go to https://aka.ms/ge
2. Make sure you're signed in with the same account as you're using with KeePass OneDrive Sync using the sign in option on the left:
![image](https://user-images.githubusercontent.com/5940670/99143972-6189bf80-2662-11eb-8089-cdd2b08c2290.png)
3. In the address field, enter:
https://graph.microsoft.com/v1.0/me/drive/sharedWithMe
![image](https://user-images.githubusercontent.com/5940670/99143958-40c16a00-2662-11eb-8f6a-4f31227eecef.png)
4. Scroll through the results at the bottom. Does this list the item you're expecting to see?
![image](https://user-images.githubusercontent.com/5940670/99143983-77978000-2662-11eb-9dde-cb007da8806c.png)

The KeePass plugin effectively makes the same call as you would do here.

**Comment by scribepl** [comment]
Ok, I logged in, but the code with the item list contains files and hosts unknown to me.

![image](https://user-images.githubusercontent.com/7255237/106330840-3e93a280-6284-11eb-97d5-9c6c35c0be24.png)


these items are not visible in the web interface. but in the browser I see items that the plug-in cannot see

**Comment by KoenZomers** [comment]
Not sure if I fully understand your response. If you try this through the Microsoft Graph Explorer and scroll through the results, do you see the folder you're expecting to see on the Shared with me tab in the KeePass OneDriveSync plugin?

**Comment by KoenZomers** [comment]
Closing as no further feedback has been received
