### ISSUE TITLE
How to use net core to call onedrive?

### ISSUE THREAD

**Issue by bbhxwl** [KoenZomers/KeePassOneDriveSync#142]
How to use net core to call onedrive?

**Comment by KoenZomers** [comment]
This KeePass plugin is not providing any .NET core and/or OneDrive direct support. Are you mixing this project up with https://github.com/KoenZomers/OneDriveAPI perhaps?

**Comment by bbhxwl** [comment]
> This KeePass plugin is not providing any .NET core and/or OneDrive direct support. Are you mixing this project up with https://github.com/KoenZomers/OneDriveAPI perhaps?

https://github.com/KoenZomers/OneDriveAPI/issues/26

**Comment by bbhxwl** [comment]
> This KeePass plugin is not providing any .NET core and/or OneDrive direct support. Are you mixing this project up with https://github.com/KoenZomers/OneDriveAPI perhaps?

I have tested both projects and can't work normally. I have an office home version account. The client is also obtained in azure_ Information like ID. It doesn't work.

**Comment by bbhxwl** [comment]
I wrote upload as updatefile.. I got it! thank you. I manually get the URL of getauthorizationtokenfromurl myself. If my program is closed, the URL will be expired and can only be obtained once. Is there any way to recycle it?

**Comment by KoenZomers** [comment]
This is about the OneDrive API. Not about the KeePass plugin. Let's continue this there instead. 
https://github.com/KoenZomers/OneDriveAPI/issues/26
