### ISSUE TITLE
[QUESTION] Failed to sync database with Onedrive

### ISSUE THREAD

**Issue by juergenff** [KoenZomers/KeePassOneDriveSync#143]
**Describe your question**
A clear and concise description of what your question is about.

**Screenshots**
If applicable, add screenshots to help explain your question.

With one of my Windows 10 clients it isn´t possible to synchonize the database on Microsoft OneDrive Personal.

Any idea how the local database could be synchronized with my OneDrive Personal?
![Second picture](https://user-images.githubusercontent.com/77242954/104131235-830edb00-5375-11eb-94e3-3a108cdb6a7e.JPG)

On my others computers and android devices the sync works fine.

**Versions (please complete the following information):**
- KeePass [2.47]:
- KeePass OneDriveSync Plugin [2.1.2.1]:

**Authentication method**
- [x] Microsoft Graph (any browser)
- [x] Microsoft Graph (built in browser)
- [x] OneDrive
- [ ] OneDrive for Business
- [ ] SharePoint 2013/2016/2019

**KeePass database synced with**
- [ ] OneDrive for Business
- [x] OneDrive Personal

**Comment by juergenff** [comment]
Here some additional files
![Second picture](https://user-images.githubusercontent.com/77242954/104215884-b0bd5800-5439-11eb-8533-eb31c7f3f266.JPG)
![Third picture](https://user-images.githubusercontent.com/77242954/104215902-b5820c00-5439-11eb-950e-710055c7fefa.jpg)
![Fourth picture](https://user-images.githubusercontent.com/77242954/104215918-b9159300-5439-11eb-98e1-2631d2bc97a1.jpg)
![Fifth picture](https://user-images.githubusercontent.com/77242954/104215931-bc108380-5439-11eb-8c52-a2fa26b549ad.JPG)

**Comment by juergenff** [comment]
The sync doesn't work and Paul from sourceforge.net wrote, 

It has to be a setting in OneDrive, but I don't have OneDrive and can't give you any tips.
cheers, Paul

**Comment by juergenff** [comment]
Can someone help me in that case?

Thanks in advance.
Jürgen

**Comment by KoenZomers** [comment]
Hi @juergenff. From the error message it looks like it's not liking the HTTPS certificate that was used for the encryption of the traffic. Typically this means you're using a proxy or network device that intercepts the HTTPS traffic. Could this be the case for you? Can you try it on a "clean" connection such as on 4G or 5G?

**Comment by juergenff** [comment]
Hi Koen, 

Thanks for your message. From my understanding it isn't a network issue on layer 2, 3 or 4 

Please read the following messages and results which I received from from Paul (SourceForge) some weeks ago.
https://sourceforge.net/p/keepass/discussion/329220/

It may be KeePass not accepting the certificate, although that should be fine with OD. Do you have certificate details?
Try KeePass Tools > Option > Advanced, File Input/Output Connections, Accept invalid SSL certificates.
cheers, Paul
________________________________________

Seems to be a setting in the plug-in.
>From the MS web site.
Parameter name  Value   Description
client_id   string  The client ID value created for your application
cheers, Paul
________________________________________

It has to be a setting in OD, but I don't have OD and can't give you any tips.
cheers, Paul
________________________________________

I've spent hours to find the root cause on a certain Windows 10 client. On my other Windows 10 clients the sync with OD works fine.

Cheers, Jürgen

**Comment by KoenZomers** [comment]
Are you familiar with Fiddler and/or Wireshark? Can you capture a trace while trying to sync? If you don't mind sharing it with me, please send it by email and don't post it here. It should reveal what's going on.

**Comment by KoenZomers** [comment]
Thanks for sharing your findings @fairking. This topic is very old already, so going to assume it is no longer needed to keep it open.
