### ISSUE TITLE
Keepass Sync error

### ISSUE THREAD

**Issue by Mikehr** [KoenZomers/KeePassOneDriveSync#144]
Hi Koen,
I have office 365 and onedrive is normally working for me some years.
Im using KP long time but I have problem with sync every time.
It concerns the size of kbdx file. Pls, see screenshot.
![KeePassError](https://user-images.githubusercontent.com/15333306/106882251-d5c28500-66de-11eb-979b-6b0d76d31237.jpg)
How can I solve it? Im using it really everyday.
Thank you.
Best regards,
Mike

**Comment by Mikehr** [comment]
It there any possibility to get over onedrive API limit 4Mb? If not it has no sense to use it for me.

**Comment by KoenZomers** [comment]
Hi @Mikehr. The OneDrive API definitely supports larger files to be sent across and so does my KeePass plugin for Windows. From your photo it looks like you're using [Keepass2Android](https://play.google.com/store/apps/details?id=keepass2android.keepass2android&hl=en&gl=US). Is that correct? That's not written or maintained by me, so for any issues with that, you would need to contact the developer of that tool: crocoapps@googlemail.com

**Comment by Mikehr** [comment]
Thank you for quick reply, 

So advice me which one is supported by you. I will install it.

Kind regards,

 

 

_____________________________________________________
Michal Hrubjak

ALLTOP s.r.o.  –  <mailto:info@alltop.pro> info@alltop.pro -  <http://www.alltop.pro/> www.alltop.pro - +421 911 666 456

**Comment by Mikehr** [comment]
Hi Koen,

 

Aaach... sorry. I didnt mention that the problem is on Android Sony phone... your windows app is working well.

Thank you.

 

_____________________________________________________
Michal Hrubjak

ALLTOP s.r.o.  –  <mailto:info@alltop.pro> info@alltop.pro -  <http://www.alltop.pro/> www.alltop.pro - +421 911 666 456

**Comment by KoenZomers** [comment]
I don't have a KeePass tool myself, just a plugin for the Windows version. I'm also using KeePass2Android for many years already and for me it's working well. My KeePass database is just 1.8 MB though, so that might be why. You really have to check with the KeePass2Android maker on trying to resolve the issue.

**Comment by KoenZomers** [comment]
Closing this issue as no further feedback has been received
