### ISSUE TITLE
[QUESTION] Plugin vs. KeePass Triggers

### ISSUE THREAD

**Issue by GraphiteWingedBird** [KoenZomers/KeePassOneDriveSync#145]
**Describe your question**
Basically wondering how the plugin works differently than just using triggers and a "Local-Master" setup as described [here](https://keepass.info/help/kb/trigger_examples.html#dbsync) .

**Screenshots**
If applicable, add screenshots to help explain your question.

**Versions (please complete the following information):**
- KeePass [e.g. 2.45]:
- KeePass OneDriveSync Plugin [e.g. 2.1.1.2]:

**Authentication method**
- [ ] Microsoft Graph (any browser)
- [ ] Microsoft Graph (built in browser)
- [X] OneDrive
- [ ] OneDrive for Business
- [ ] SharePoint 2013/2016/2019

**KeePass database synced with**
- [ ] OneDrive for Business
- [X] OneDrive Personal

**Comment by KoenZomers** [comment]
Not familiar with the triggers approach you reference myself, but briefly reading through it, it looks like a somewhat similar process what my plugin would do. It also downloads the latest KeePass file first, merges it with the local copy and then uploads the merged version back to the cloud location. This will avoid that databases can get corrupt or entries lost. I guess if you prefer using purely out of the box functionality, the triggers approach could suffice as well. Again, never used it myself so can't judge about how well it works.

**Comment by GraphiteWingedBird** [comment]
Thanks for looking into the triggers, even if briefly. I suppose I forgot plugins existed for KeePass as I've been using it out of the box for so long (and non-synced/non-cloud). I only set up the triggers recently, but it seems to work - however I'll also give your plugin a try and maybe I can learn a thing or two.
