### ISSUE TITLE
[BUG] Check for an update => Status Error

### ISSUE THREAD

**Issue by Silverstone999** [KoenZomers/KeePassOneDriveSync#151]
**Describe the bug**
When i start an update ckeck, Keepass shows an errorfor KeePassOneDriveSync

**To Reproduce**
1. Go to help
2. Click on check for updates
3. See an error in update result list

**Expected behavior**
See attached screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/93727108/140377101-9639a7a5-7b78-4c52-984a-dddd721f4155.png)

**Versions (please complete the following information):**
- KeePass 2.49
- KeePass OneDriveSync Plugin 2.1.1.2

**Authentication method**
- [ ] Microsoft Graph (any browser)
- [X] Microsoft Graph (built in browser)
- [X] OneDrive
- [ ] OneDrive for Business
- [ ] SharePoint 2013/2016/2019

**KeePass database synced with**
- [ ] OneDrive for Business
- [X] OneDrive Personal

**Comment by MichaelMommertz** [comment]
I've noticed it since downloading the latest version from here a few days back so it might just be the latest .plgx file on the server which is 3.11MB.

**Comment by KoenZomers** [comment]
Thanks for reporting this guys. This error shows because the plugin is configured to check for updated on a server that I have recently removed from a datacenter. I will need to update the code to check for the version on GitHub instead. Will do so when I get a chance.

**Comment by KoenZomers** [comment]
Fixed in [2.1.2.2](https://github.com/KoenZomers/KeePassOneDriveSync/releases/tag/2.1.2.2)
