### ISSUE TITLE
[BUG] SharePoint (Online) connectivity fails

### ISSUE THREAD

**Issue by eburgers81** [KoenZomers/KeePassOneDriveSync#157]
**Describe the bug**

**To Reproduce**
1. Go to 'One Drive Sync Configuration'
2. Click on 'Sync Rule''
3. Click 'Yes' to stat syncing
4. Setup new SharePoint Connector details
5. Fill in SharePoint URL, ClientID and Client Secret
6. Click 'Test Connection'

![image](https://user-images.githubusercontent.com/100222902/186874373-cf6ecd69-9a53-4e4c-bf47-476a320fb7b5.png)

8. Connection is successfully setup
9. Click 'OK'
10. Click 'OK'
11. Error Shows

![image](https://user-images.githubusercontent.com/100222902/186874527-b3c78cb7-0bcc-49e7-ad9f-fc6b05feda60.png)

**Expected behavior**
A succesfull SharePoint sync

**Screenshots**

**Versions (please complete the following information):**
- KeePass [2.51.1]:
- KeePass OneDriveSync Plugin [2.1.2.2]:

**Authentication method**
- [ ] Microsoft Graph (any browser)
- [ ] Microsoft Graph (built in browser)
- [ ] OneDrive
- [ ] OneDrive for Business
- [X] SharePoint Online

**KeePass database synced with**
- [X] OneDrive for Business
- [ ] OneDrive Personal

**Comment by KoenZomers** [comment]
Can you give it a try while entering the SharePoint url to just the site collection? In the screenshot it shows you entered the url to the document library instead.

**Comment by eburgers81** [comment]
Thanks, this seems to be the solution :)
