### ISSUE TITLE
SharepointOnline

### ISSUE THREAD

**Issue by katagaStyle** [KoenZomers/KeePassOneDriveSync#17]
Hi, 

is there a way to use Sharepoint online instead of OneDrive? 

Thank you in advance.

**Comment by KoenZomers** [comment]
At this moment, only if you would be using the OneDrive for Business component of SharePoint Online. Storing databases on i.e. Teamsites is currently not possible.

**Comment by KoenZomers** [comment]
I have added storing databases on TeamSites to the todo list.
