### ISSUE TITLE
Plugin does not work with version 2.33

### ISSUE THREAD

**Issue by albgen** [KoenZomers/KeePassOneDriveSync#18]
Latest version released yesterday(2.33) is not working with the plugin.

Please update.

**Comment by KoenZomers** [comment]
Can you elaborate what doesn't work for you? I just upgraded to 2.33 here and the plugin still seems to work fine.

**Comment by albgen** [comment]
![error](https://cloud.githubusercontent.com/assets/7231968/15115668/181d7584-15ce-11e6-8067-f8f39fb60f49.png)

**Comment by albgen** [comment]
I was not upgrading the KeePass.exe.config so thats why i got that error. Now everything works fine.

**Comment by KoenZomers** [comment]
Ok, glad the plugin is still okay :)
