### ISSUE TITLE
Request for Product Enhancement: File Picker

### ISSUE THREAD

**Issue by jpickerell** [KoenZomers/KeePassOneDriveSync#19]
Any chance of there being plans to add a file picker to the plugin?

Not a huge deal as it can always be figured out and done manually as it is now. Having a file browser/picker GUI would just make it a little easier to use.

I don't often add a new machine or new KeePass database to previous machines. But, the infrequency of doing that means that it takes me a few minutes to remember the file path format, get that path, and put it into the plugin config.

**Comment by KoenZomers** [comment]
It has been on my wish list for a while already too :) But being busy with a lot of different things and like you say, it's not something you to do often and is completely difficult, I don't get to spend my attention on it. Hopefully I will, some day! :)

**Comment by KoenZomers** [comment]
A file picker has been introduced in 1.5.0.0! :)

**Comment by jpickerell** [comment]
@KoenZomers, just wanted to come back and say thanks for adding this back in August 2016! I was quite happy to see it as soon as you added but never took the time to thank you!
