### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by Kyrodan** [KoenZomers/KeePassOneDriveSync#2]
Hi Koen,

I did not find any license information in this repository.
Could you please clarify how your code is licensed?
Please add proper licensing information to your project, e.g. a LICENSE.md, headers in code, etc..

Thanks,
Daniel

**Comment by KoenZomers** [comment]
Hi Daniel,

I've just added the Eclipse license to the code.

**Comment by Kyrodan** [comment]
Ok, thanks.

**Comment by Kyrodan** [comment]
An additional question:
Is the Eclipse License the right choice for KeePass (which is GPL'd)?
I'm not a lawyer, so I'm not sure. I just read that EPL and GPL are not seen to be compatible.

**Comment by KoenZomers** [comment]
I have no idea how that works either. My thought was that since I'm not using/extending KeePass code, I'm just talking to it, I'm fine to pick any license and this one seemed appropriate to me. If not and somebody complaints I will modify it again.
