### ISSUE TITLE
NullReferenceException after opening a database

### ISSUE THREAD

**Issue by jiri-matejka** [KoenZomers/KeePassOneDriveSync#20]
Hi,
I encountered NullReference exception when opening database that is in OneDrive. The database is already connected to OneDrive. 
I have actually two Keepass databases (work and personal), both connected to OneDrive, but each to different Live account. This exception happens only with one of the files (opened alone).
I have upgraded to version 1.6 but still this is happening.
Sorry for the stack trace being in Czech :/

System.NullReferenceException: Odkaz na objekt není nastaven na instanci objektu.
   v KoenZomers.OneDrive.Api.OneDriveApi.<DownloadItemAndSaveAs>d__86.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   v KoenZomersKeePassOneDriveSync.KeePassDatabase.<SyncDatabase>d__17.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v KoenZomersKeePassOneDriveSync.KoenZomersKeePassOneDriveSyncExt.<OnKeePassDatabaseOpened>d__7.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

### Loaded assemblies
(only excerpt with the most important ones; ask for complete list if needed)

mscorlib
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.6.1080.0 built by: NETFXREL3STAGE
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

KeePass
    Verze sestavení: 2.32.0.23563
    Verze Win32: 2.32.0.0
    Základ kódu (CodeBase): file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.exe

System.Windows.Forms
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.6.1038.0 built by: NETFXREL2
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

KoenZomers.OneDrive.Api
    Verze sestavení: 1.6.4.0
    Verze Win32: 1.6.4.0
    Základ kódu (CodeBase): file:///C:/Users/DELL/AppData/Local/KeePass/PluginCache/UAxlwXTCmLysUQa1YZnp/KoenZomers.OneDrive.Api.DLL

**Comment by KoenZomers** [comment]
Hi there. Could you add detailed repro steps about what you do to get this error so I can try to reproduce the issue on my end?

**Comment by KoenZomers** [comment]
Closing this issue as no response has been received.
