### ISSUE TITLE
Handle password changes

### ISSUE THREAD

**Issue by bar-foo-x** [KoenZomers/KeePassOneDriveSync#21]
This is more of a feature (or perhaps documentation) request: there doesn't seem to be an elegant way of handling changes to the Live account password. As far as I can tell, the only way to deal with it is to delete the connection to OneDrive and reestablish it. Ideally there would be an option to reconnect to the account, but failing that a brief explanation on the website of the appropriate steps would be helpful. Thanks.

**Comment by KoenZomers** [comment]
I managed to easily reproduce this. Changing your password invalidates all existing oAuth refresh tokens. I have just released version 1.6.2.0 of the plugin in which this has been fixed. It will now simply prompt for the login dialog again when this happens so you can log in with your new credentials.
