### ISSUE TITLE
Failed to connect to OneDrive

### ISSUE THREAD

**Issue by Olli2k** [KoenZomers/KeePassOneDriveSync#22]
Got a connection issue with new 1.7 Version of your plugin. Downgrading to 1.6 fixes this issue.
![hc_341](https://cloud.githubusercontent.com/assets/22831306/19426929/a2238d86-9440-11e6-8c10-dbe6fbb8dc9c.jpg)

**Comment by KoenZomers** [comment]
Thanks for reporting this. Can you give me a little more detail to work on? Are you using a proxy? If so, which mode do you have the proxy settings set to in the KeePass proxy configuration?

**Comment by Olli2k** [comment]
Well, directly good hint ;). I had just tested 1.7 on my office Workstation. Due to company network there is a proxy yes and KeePass is setup to use system settings for proxy. 
At this configuration it is not working (1.6 does!).

Due to your info, I tested 1.7 at home. Without proxy it works.

**Comment by KoenZomers** [comment]
I made quite a bit of changes in the proxy code and had one other person already tell me that something didn't work anymore. I'll probably need to revert some changes I've done. Let me work on that and share a prerelease version with you to see if that fixes it again.

**Comment by KoenZomers** [comment]
Would you mind testing this plugin to see if it fixes your proxy issue? 

[KeeOneDriveSync.zip](https://github.com/KoenZomers/KeePassOneDriveSync/files/532876/KeeOneDriveSync.zip)

**Comment by Olli2k** [comment]
It works again! Proxy setup is no more problem.

**Comment by KoenZomers** [comment]
Thanks for testing. I now noticed that I broke the manual proxy configuration. I've made some code changes to fix that. Could you verify again with this plugin to see if your proxy usage also still works?

[KeeOneDriveSync.zip](https://github.com/KoenZomers/KeePassOneDriveSync/files/533480/KeeOneDriveSync.zip)

**Comment by Olli2k** [comment]
New 1.7.1.0 works as well.

**Comment by KoenZomers** [comment]
Thanks! I'll release it 👍
