### ISSUE TITLE
Does not work with mono 4.6.1

### ISSUE THREAD

**Issue by maz-1** [KoenZomers/KeePassOneDriveSync#24]
This plugin does not work with mono 4.6.1 on Arch Linux
When I came to the choice for onedrive and onedrive bussiness and click on one of them, a popup window says that "Failed to connect to Onedrive: object reference not set to an instance of an object"

**Comment by maz-1** [comment]
![screenshot_20161124_191714](https://cloud.githubusercontent.com/assets/5277060/20596679/a860ee02-b27a-11e6-9126-80ba2dbcce52.png)

**Comment by KoenZomers** [comment]
I'm sorry but this plugin is not supported on mono. I don't have access to or knowledge of such an environment, so won't be able to troubleshoot it. I'm guessing it's not supporting the new .NET functionality added in the .NET 4.5 framework as that comes into play around that step.
