### ISSUE TITLE
Syncing with wrong database

### ISSUE THREAD

**Issue by drujd** [KoenZomers/KeePassOneDriveSync#25]
When using KeePass with multiple databases (such as personal and work), if you save current db and immediately switch to another database, synchronization is done between the local version of one and cloud version of the other one! In my case (dbs have different passwords) this only results in error prompt (composite key is invalid), but in case both databases have identical passwords, this could potentially result in synchronization and merge of the 2 dbs.

**Comment by KoenZomers** [comment]
Thanks for letting my know. I'll try to reproduce this on my end.

**Comment by KoenZomers** [comment]
I can reproduce this behavior. I'll try to see what I can do to prevent it from happening.

**Comment by KoenZomers** [comment]
I've added an extra check after downloading the database and before doing the actual merge if the currently selected database is still the one that we want to merge. If not, it will abort the sync and not do the merge. That's the best I can do as the KeePass API won't allow me to switch to another KeePass database that is currently not the selected/open one. Will release it shortly in v1.8.0.0.

Thanks for bringing this to my attention!
