### ISSUE TITLE
Faq entry to highlight version conflict handling

### ISSUE THREAD

**Issue by nmbradford** [KoenZomers/KeePassOneDriveSync#27]
Hi - really impressed with this plugin.  Id assumed initially, that last write to a shared database would win - atomically overwriting a concurrently modified version elsewhere and potentially losing edits as a result.  

I was impressed to find that the plugin handles merging of differing versions of the database (at least two different, (but concurrently created on different machines) items were merged into the database after synchronising when I tested it, when Id expected one of them to be lost.

I didn't find any documentation stating expected behaviour here though, and details of how it handles merge conflicts (edits to the same item seem to behave as a last write wins...).  Would be a good FAQ?

Cheers for the plugin though!

**Comment by KoenZomers** [comment]
Thanks for the compliments and feedback! Good idea. I'll add it to the FAQ.
