### ISSUE TITLE
Choosing Key file when Syncing New Database

### ISSUE THREAD

**Issue by IkerGimenez** [KoenZomers/KeePassOneDriveSync#29]
This is mostly an enhancement, but it would be nice to have a more streamlined option of including a key file to the initial process of adding a database hosted on OneDrive. When syncing it at first, it only asks for the .kdbx file, but then when the password prompt asks for the key file, I can't navigate to OneDrive to get the key file. Having an option to save the key file locally along with the database file would be nice.

**Comment by KoenZomers** [comment]
Hi @IkerGimenez. Interesting request. I see what you mean, but in my opinion it makes no sense to store the key file on the same platform as you store your KeePass database. It's like adding an extra lock to your door, but leaving the keys in it. The key file is meant to add an extra complexity to gain access to your database. An attacker would need access to the key file AND your password. If you store the key file with your database, you may just as well not lock your database with it.

What do you think?

**Comment by IkerGimenez** [comment]
Koen, I'd never really thought of it that way, but you're right, it does defeat the purpose of having a key file. Unless someone comes up with a good reason, I think we can close this issue.
