### ISSUE TITLE
OneDrive API key in source code

### ISSUE THREAD

**Issue by Kyrodan** [KoenZomers/KeePassOneDriveSync#3]
Your OneDrive API key is checked in in file KoenZomers.KeePass.OneDriveSync/KoenZomersKeePassOneDriveSyncExt.cs

I think you should keep you API key secret and change it ASAP.

Regards,
Daniel

**Comment by KoenZomers** [comment]
Hi Daniel,

there's no way to write open source code that interacts with OneDrive without putting the API key readable in the code. By itself that's not an issue as it doesn't grant you access to anything. This API key can only be used to request access to a OneDrive. And when doing so, the user still must explicitly grant this access. Only the combination of the refresh token coming forward from the grant and the API key gives access to one particular OneDrive.

So no worries :)

**Comment by Kyrodan** [comment]
Hmm, but now I can write a malware that mimics to be the original KeePassOneDriveSync with *your* registered app key. I think that's much more evil than guiding contributors how to obtain their own "debug" key.

Even Microsoft clarifies this in https://dev.onedrive.com/app-registration.htm:
> Important Treat the value of client secret the same as you would a user's password. The secret represents the key to your application and, if made available, can be used to impersonate your application.

**Comment by KoenZomers** [comment]
True, but again, its open source. Even if I would remove it from the open source, but still would use it in the KeePass plugin, it's a breeze to reverse engineer it and get it anyway and it would break the open source license since I'm distributing a different binary than which I'm exposing the source of.

**Comment by Kyrodan** [comment]
Even if it's open source the license terms for using any commercial APIs I know forbids making it public available. So I disagree with your opinion in both points:
* For me Client ID and ClientSecret is just data that *never* should to be stored in *any* source code (public available or kept secret in my home attic)
* Yes, it is a problem to keep it secret - there are many discussions regarding that
* Because of the first point: if you are doing it "right", you have no problem with your compiled code (IMHO)

But to make the story short: it's your decision - I just wanted to state you to the direction of a possible security risk.

**Comment by KoenZomers** [comment]
Sure, thanks for sharing your opinion.

I will leave it as is.
