### ISSUE TITLE
relative paths

### ISSUE THREAD

**Issue by bitmk2** [KoenZomers/KeePassOneDriveSync#34]
Is it possible to support relative paths for the database file? I need to move a portable copy of my keepass with its plugins inside a usb stick. Sometimes it will mount as D: but on another computer F: or E: is also possible.

**Comment by KoenZomers** [comment]
Relative paths are already implemented. Just be sure to place your KeePass database file anywhere in the same folder as KeePass.exe or any folder underneath it.

**Comment by bitmk2** [comment]
True. My database file existed outside the Keepass.exe folder and "../" did not work.
