### ISSUE TITLE
still no mono?

### ISSUE THREAD

**Issue by boistordu** [KoenZomers/KeePassOneDriveSync#35]
Still no mono support? 
Would you maybe just have some vm with linux installed and test it with different mono version ?

**Comment by KoenZomers** [comment]
Nope, sorry. It's also not on my roadmap to add support for running with mono. I don't have a Linux VM, nor the know-how to set one up, nor did I get more than a handful requests to make this suitable for mono.

**Comment by colin-kiegel** [comment]
Would it be a compromise to keep a github ticket "Linux Support" with `help wanted` label around? This might attract a new contributor. ;-)

**Comment by KoenZomers** [comment]
Hi @colin-kiegel, sure. Although it's probably a better idea if somebody with the skills has interest in doing so to fork from my code and create a separate version for mono. The code is already quite complex and I'm afraid trying to merge it in this version will make the maintainability even worse.

If anybody reading this has the skills and interest to give this a try, please share here.

**Comment by J-O-P** [comment]
I just installed a new Debian 10.4 Linux PC and installed KeePass (v2.45)  together with my favorite plugin KeePassOneDriveSync (v2.1.2.1). Initially I got an error saying the plugin is not compatible, but the error message indicated that installing "mono-complete" might help in certain situations. So I installed *mono-complete" via apt. 

Result:  It works!  

I was able to open my DB from OneDrive and use KeePass as on my Windows system. It syncs with OneDrive as it should. 
So far everything looks good. But no extensive experience yet.

**Comment by KoenZomers** [comment]
That's amazing! Thanks for sharing. I bet the built in browser option for connecting may get you into trouble, but using the any browser option which is recommended anyway should be good. Can you share more details on how to get this to work so I can add it to the documentation? What's the exact command you run to install this mono-complete?

**Comment by J-O-P** [comment]
A few more notes on my setup: 
- Indeed I used the "any browser" option for the authentication with my OneDrive (Business). I have not yet tried anything else. 
- The Debian package of KeePass is a bit outdated (v2.41). Initially I thought the "plugin not compatible"-error would come from this old version. So I manually replaced the "KeePass.exe" file in /usr/lib/keepass2 with the current version (v2.45).
- The additional installation of mono-complete is straightforward with "sudo apt install mono-complete"
- For the KeePass autotype feature to work properly to need to install "xdotool" as well (there is a message indicating this on first try) and you need to manually setup the global hotkey, but this is usual for KeePass on Linux as documented and not related to this plugin.

**Comment by KoenZomers** [comment]
Thanks for sharing @J-O-P! I've added a reference to your information at the [system requirements page](https://github.com/KoenZomers/KeePassOneDriveSync/wiki/System-Requirements).

Will proceed with (finally! :) ) closing this issue.

**Comment by waSimosS** [comment]
I confirm @J-O-P, I succeeded to set the sync with the KeePassOneDriveSync on my ubuntu 18.04. Thank you!

**Comment by dragonruler1000** [comment]
This works for me on fedora after installing mono-complete.
