### ISSUE TITLE
Configuration window isn't getting focus

### ISSUE THREAD

**Issue by milnak** [KoenZomers/KeePassOneDriveSync#36]
Tools > OneDrive Sync Options
the configuration window seems hidden.
I alt-tab around and once I get back to KeePass it finally shows up.
Windows 10 1709 (17025.1000)

**Comment by KoenZomers** [comment]
Thanks for reporting this. I don't have a machine yet on this build. I recon it's the insider preview fast ring release? Can you confirm?

**Comment by KoenZomers** [comment]
Closing due to no response
