### ISSUE TITLE
Target file doesn't include ".kdbx" extension

### ISSUE THREAD

**Issue by milnak** [KoenZomers/KeePassOneDriveSync#38]
"/drive/root:/Documents/KeePass"

shouldn't that be

"/drive/root:/Documents/KeePass/<local filename with extension>", e.g. "/drive/root:/Documents/KeePass/MyDatabaes.kdbx" ?

**Comment by milnak** [comment]
looks like I must have configured this incorrectly originally -- I see there's other similar issues around the file picker UI.  Feel free to resolve this.

**Comment by KoenZomers** [comment]
Hi @milnak, the KeePass file gets exactly stored with the filename as you enter it in the dialog. There are people who don't want to give it the explicit .kdbx extension so to hide that it's a KeePass database file. So this behavior is as intended.
