### ISSUE TITLE
Use of NuGet packages

### ISSUE THREAD

**Issue by Kyrodan** [KoenZomers/KeePassOneDriveSync#4]
Maybe you could use public available NuGet packages instead of adding binary files to the repository.

**Comment by KoenZomers** [comment]
Can you indicate which binary file(s) you are referring to?

**Comment by Kyrodan** [comment]
CredentialManagement.dll => https://www.nuget.org/packages/CredentialManagement/
Newtonsoft.JSON.dll => https://www.nuget.org/packages/Newtonsoft.Json/
KoenZomers.OneDrive.Api.dll => your own - currently not in official nuget repository

**Comment by KoenZomers** [comment]
They're all NuGet packages. The way however how the tool released by the maker of KeePass works to compile a KeePass plugin requires all referenced assemblies to be in the same folder as the code. The way NuGet places assemblies is having them in a separate folder alongside with the code. This doesn't work for the KeePass Plugin compiler, so I need to put the assemblies in manually unfortunately.

**Comment by Kyrodan** [comment]
I haven't tried it by myself, but the the documentation of KeePass says:
> Referenced custom assemblies support. Third-party assemblies required by the plugin (references to DLLs) are supported, provided that the third-party assembly is located in the plugin source code directory (or any subdirectory of it).

**Comment by KoenZomers** [comment]
Exactly, that's the part I was talking about. That isn't the case with NuGet.

**Comment by Sebazzz** [comment]
You would however be able to download the NuGet packages as part of the build script, preventing the need to store any binary in the repository.

**Comment by Kyrodan** [comment]
At first: this plugin is relative small, so it's no need to complicate things.

On the other hand:
Using NuGet for what @Sebazzz stated (and I had this idea in mind) is the right direction and makes maintaining a project more easily. Maybe we should ask the KeePass's author to respect NuGet dependencies (after they are downloaded by NuGet itself) in compile process. 

For the meantime it could be a solution to extend the  create-plgx.cmd to _first_ copy the sourcecode and used NuGet dependencies to a temporary KeePass-Compile directory.

**Comment by Kyrodan** [comment]
I found a good solution which completely integrates into MSBuild:
https://github.com/dlech/KeePassPluginDevTools

I integrated it in my fork and it works as expected.

**Comment by downerboy** [comment]
Configure NuGet to change where it places the referenced NuGet DLLs instead of default configuration, which places them at the .sln location.  Or, you use sym links in the project bin folder that point to the appropriate NuGet locations.  

*  http://docs.nuget.org/consume/nuget-config-settings
* http://docs.nuget.org/Consume/Package-Restore

**Remember to checksum and verify the integrity of the referenced files**
