### ISSUE TITLE
Removing plgx and zip from solution as they will now be published through GitHub Releases

### ISSUE THREAD

**Issue by Olli2k** [KoenZomers/KeePassOneDriveSync#41]
Sry, but there is no readme, manual or something else, how installation should be done, without plgx. So: How to install this plugin since version 1.8.3 ??

**Comment by KoenZomers** [comment]
https://github.com/KoenZomers/KeePassOneDriveSync/blob/master/Installaton%20Instructions.md

**Comment by KoenZomers** [comment]
Closing this thread as I haven't heard back if you're still facing challenges after reading the installation steps.
