### ISSUE TITLE
OneDriveFilePickerDialog not showing 'Shared with me'

### ISSUE THREAD

**Issue by loskutak** [KoenZomers/KeePassOneDriveSync#43]
This is a feature request more than an issue.
When using **OneDrive for Business** to share database between users, the File picker dialog is not showing '_Shared with me_' content and therefore the sharing is not possible.
The KeePassOneDriveSync FAQ [suggests](https://github.com/KoenZomers/KeePassOneDriveSync/blob/master/Faq.md#can-i-share-one-keepass-database-with-friendsco-workersfamily-without-having-to-share-my-credentials-to-my-onedrive) to use 'Add to my OneDrive' option, that is not available in OneDrive for Business and could be specific only for OneDrive Personal as the answer suggests.
The Graph API [allows](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/drive_sharedwithme) for browsing the shared files, but it has to be handled using the remoteItem facet.
The KoenZomers.OneDriveAPI.OneDriveGraphApi already has [GetSharedWithMe()](https://github.com/KoenZomers/OneDriveAPI/blob/master/Api/OneDriveGraphApi.cs#L664) method.

**Comment by KoenZomers** [comment]
Nice one. I'll look into implementing it.

**Comment by KoenZomers** [comment]
It has been an insane amount of work, but this is now implemented. The APIs differ a lot between Graph, File API (OneDrive for Business) and OneDrive API (OneDrive Personal), so I've found out. So I needed to code quite a bit of ugly stuff to get it to work with all the possible combinations. There are starting to be so many variants of possible scenarios that I probably have missed some in my testing. Can you test the latest plugin and see if it works for you?

One note: you need to use the Graph API if you want to use the Shared with me from OneDrive for Business. There's a bug in the native OneDrive for Business API which prevented me from getting it to work fully in that scenario. The Graph API is the recommended choice anyway, so it should not be a problem.

**Comment by loskutak** [comment]
Hi,
Wow, didn’t expected that level of hassle, well done!
We’ll test it next week.
Thanks,

//Tomáš

**Comment by RobMahn** [comment]
I am using OneDrive Personal and have wanted to to share a file with my spouse.

1. I shared my database file with her.
2. On her computer, under her Windows login, I downloaded a copy of my shared database from OneDrive and opened the local file with KeePass.
3. After entering the password, I was prompted to "Start syncing with OneDrive.  I left the radio button on "Yes", and clicked OK.
4. On the OneDrive tab, I clicked the icon for "Microsoft Graph - One Drive and One Drive for Business"
5. I was then prompted to select an account, and picked my account, the only one showing in the list.  It showed "Signed in".
6. I answered "YES" to let this app access my info.
7. Under "Select location", "Shared with me" tab, I selected my shared database.
8. KeePass downloaded and syncronized the file.
9. Then I received the error "Failed to sync database: Object reference not set to an instance of an object."
10. The OneDriveSync Configuration shows the Romote KeePass path as //KeePassRFM.kdbx/KeePassRFM.kdbx".  This is a repeatable problem.
11. Then I tried to use the "Other", "OneDrive" method of opening the file, and received the same error.

I am happy to be of assistance collecting logs, testing, or working with remote access.

**Comment by KoenZomers** [comment]
@RobMahn, thanks for sharing these detailed steps to reproduce.

Regarding step 10, this is just a visual thing although it's ugly. It was extremely hard for me to fix that, so I decided to release the functionality and leave this visual impairment. Hope to fix it in a future version.

Can you create a new empty KeePass database for me and follow the exact same steps while running Fiddler and have it capture the HTTPS traffic? The traffic log will help me a lot to find out where things to wrong. Please share the Fiddler trace through e-mail (koen@zomers.eu) and not publicly here as it contains a token which provides access to that file you shared.

**Comment by KoenZomers** [comment]
Closing as no response has been received
