### ISSUE TITLE
Version incorrect on dll in ZIP file for release 2.0.0.1

### ISSUE THREAD

**Issue by mvancamp** [KoenZomers/KeePassOneDriveSync#44]
I've downloaded the zip file for release 2.0.0.1 and when unpacked the KoenZomersKeePassOneDriveSync.dll has a version 1.8.1.0 (which is less than the latest, already installed, plugin on my PC (1.8.3.0)... Therefore I hesitate to replace it with the current installed plugin.

**Comment by mvancamp** [comment]
During unpacking of the ZIP, something went wrong... hence no panic... all is OK, sorry for this... my fault!

**Comment by ChrSch84** [comment]
https://github.com/KoenZomers/KeePassOneDriveSync/releases/download/2.0.0.1/KeeOneDriveSync.plgx this File is the Old 1.8.1.0 File.

Only in the Master ZIP File you get the RIGHT Version. Please Fix.

**Comment by KoenZomers** [comment]
@ChrSch84, can you download the latest release of this plugin? I double checked to ensure the latest versions of the DLLs are in there.

**Comment by KoenZomers** [comment]
@ChrSch84, haven't heard back from you but have received signals that this issue should no longer apply to the latest release. I will therefore close this topic. If it does still happen for you, feel free to reopen.
