### ISSUE TITLE
Plugin v2.0.0.1 not being loaded by Keepass 2.38

### ISSUE THREAD

**Issue by Tim-Morton** [KoenZomers/KeePassOneDriveSync#45]
v2.0.01 of the KeePassOneDriveSync Plugin is not being recognised by KeePass 2.38 and does not appear in the plugins list once KeePass is open (I think it was also not working with 2.36)

I don't think this is a version problem but some sort of corruption that is causing KeePass not to see the plugin.  It was working beautifully and I didn't notice that it had stopped for a while.  

Can you please advise if there is a way of stripping-out any configuration details that might be stopping it from working?  I have tried uninstalling KeePass and re-installing it, but it didn't make any difference.
I have also checked that KeePass is loading other plugins and it is working OK for others, just not KeePassOneDriveSync.

Just for info, I opted to keep the key in the database when I set it up, so I may have to remove that somehow to start again - if this is the case, would you please advise how to do this?

Many thanks
Tim

**Comment by KoenZomers** [comment]
Hi @Tim-Morton,

Are you using the portable version of KeePass or the installer?
Are you using the plgx or DLLs of the plugin?
If you create a new KeePass database, does the plugin with it?

**Comment by Tim-Morton** [comment]
Hi @KoenZomers ,

Thanks for getting back to me so promptly. 

- I am using the installed version of KeePass with the plgx version of the plugin (I have updated to 2.0.1.1 after you posted it last night).
- I have created a new KeePass database as a test but there is no change in the behaviour of the plugin - it is as though KeePass cannot 'see' it in the plugins folder. 
- I have also tried removing the plgx version and using the DDL set for version 2.0.1.1 - KeePass still doesn't parse the plugin (but it does parse other plugins).
- I tried uninstalling KeePass and even tried re-installing in a new folder but got the same outcome with both the plgx and the DLL versions (I have not mixed the DLL version and the plgx version).

I am really stuck - do you have any ideas?

Kind regards
Tim

Here is a bit more detail about my environment:
Windows 10 v1709 Build 16299.192
KeePass 2.38 (installer version)
KeePassOneDriveSync 2.0.1.1
.Net framework 4.7.1

**Comment by KoenZomers** [comment]
That's odd. Can you check if the file is perhaps blocked? Right click on the PLGX inside your plugins folder (C:\Program Files (x86)\KeePass Password Safe 2\Plugins). At the bottom of the general tab there may be an option to unblock it. If that's shown, unblock it and restart KeePass to see if it picks it up. If the option is not shown, it's not blocked.

**Comment by Tim-Morton** [comment]
Sorry - no sign that the file is blocked:
(If this image works, you will see a screenshot of the properties box)

![image](https://user-images.githubusercontent.com/35332532/34877742-352f0fe8-f79f-11e7-9a23-ad1718c78b8f.png)

**Comment by KoenZomers** [comment]
At the bottom right you'll see Unblock. Tick that box and close it with OK. Try again after that.

**Comment by Tim-Morton** [comment]
Oh DOH! I read the 'Unblock' the wrong way! It's working now - thank you Koen 👍

**Comment by KoenZomers** [comment]
Yay! I've added these instructions to the FAQ: https://github.com/KoenZomers/KeePassOneDriveSync/blob/master/Faq.md#keepass-doesnt-detect-the-plugin . Strangely on my machines it doesn't matter if it's blocked or not, it will always pick it up. May have something to do with the UAC settings on the machine I guess.

**Comment by Tim-Morton** [comment]
That's cool - I feel a bit of a fool for not thinking of it myself!  

I am trying to follow good practice and have my normal user account set with no administrative privileges, but I only set it up that way over the xmas holiday - I expect it was that change that caused the plugin to be blocked when I downloaded 2.0.0.1 (though it doesn't explain why it didn't block the second plugin, which I only downloaded as a test to see if KeePass itself was not working properly).

Thanks again for your help

**Comment by KoenZomers** [comment]
No worries. I know that feeling that you sometimes just miss the easy things because you're straightaway thinking about the hard things :)
