### ISSUE TITLE
Path too long

### ISSUE THREAD

**Issue by sandro730** [KoenZomers/KeePassOneDriveSync#47]
Hello

I'm using KeePass with your plugin on a usb card.
My databe file is in:
F:\Programmi_Home\KeePass2\DataBase

The first part of the path is truncated in the configuration file.
As if the generated string is too long.
<Value> {"rogrammi_Home\\KeePass2\\DataBase ........ rageType": 2}} </ Value>

Your plugin will not work if the database is on an SFTP path.
SFTP: // <Server Name: // <Path> / ......

Is it possible to implement this possibility?

Thank you
Sandro

**Comment by KoenZomers** [comment]
Hi @sandro730,

I'll consider looking into the possibility to add support for SFTP. So far you're the first one to request it.

Are you pointing out an issue with the path as well? It's not completely clear to me. If you are trying to address an issue, please provide a bit more information about it. What's the error you're getting? Are you using the portable version of KeePass? Through what storage provider are you trying to sync your database?

**Comment by sandro730** [comment]
Thank you
I use KeePass portable.
On a usb key.
I use OneDriver.
The error is unable to synchronize the database.

[Immagine](https://1drv.ms/i/s!AtkEcdQQ-bz-ghtpveSp3tkdKgET)

**Comment by sandro730** [comment]
I tried to change the path to the usb key.
Error is...
Failed to sync database. Unable to find part of the route:

See Images.
[Immagine 02](https://1drv.ms/i/s!AtkEcdQQ-bz-gh0T6xfJiUZrpcr1)
[Immagine 03](https://1drv.ms/i/s!AtkEcdQQ-bz-ghy5-N_AFy1alL52)

Thank you

**Comment by sandro730** [comment]
Hello

Do you need more information ?
Do you need some specific tests ?
Describe the test I can perform.

Thank you

**Comment by KoenZomers** [comment]
Closing as no response has been received
