### ISSUE TITLE
Failed to sync database: La référence d'objet n'est pas définie à une instance

### ISSUE THREAD

**Issue by cgandat** [KoenZomers/KeePassOneDriveSync#48]
Hello,

With the latest version of KeePassOneDriveSyncc (2.0.1.1) and KeePass 2.38, I cant sync anymore with my database. I've got this message: Failed to sync database: La référence d'objet n'est pas définie à une instance

**Comment by KoenZomers** [comment]
Hi @cgandat, can you provide a bit more information? Which cloud provider are you syncing through? Have you tried removing the config and setting up the sync again? Most likely that will fix it already. I had to make some major changes in the last few versions to introduce new functionality. Unfortunately I couldn't test all upgrade scenarios so you may have hit one that doesn't go smooth. Again, resyncing probably fixes it.

**Comment by cgandat** [comment]
> Have you tried removing the config and setting up the sync again?

By doing that, it works again. Thanks

**Comment by KoenZomers** [comment]
Thanks for confirming @cgandat!
