### ISSUE TITLE
Why do you use your own OneDriveAPI wrapper instead of existing ones?

### ISSUE THREAD

**Issue by Kyrodan** [KoenZomers/KeePassOneDriveSync#5]
Hi,

I saw you wrote your own OneDriveAPI wrapper. What are the pros and cons in contrast to existing alternatives like https://github.com/saguiitay/OneDriveRestAPI?
I like the idea of participating in existing projects/frameworks rather than reinventing the wheel.

Regards,
Daniel

**Comment by KoenZomers** [comment]
Completely agree. I started building the OneDrive API wrapper to get a full and thorough understanding of the inner workings myself. I've used it for internal projects only and then decided to use it for this plugin as well. So in general, I'm in favor of reuse, in this scenario, the reuse applied as well, but coming from a different angle.

**Comment by Kyrodan** [comment]
Ok, as long as it works there is no need to change.
