### ISSUE TITLE
Plugin in Portable version

### ISSUE THREAD

**Issue by Ich5003** [KoenZomers/KeePassOneDriveSync#52]
Hey,
the plugin does not work correctly on portable installations.
I'm using KeePass 2.38 portable on my USB drive.
When opening the database it says "Failes to sync".

After Pressing Ctrl+S it starts sync which works.

With the regular installed version everything works as expected.

Thank you,
Lucas

**Comment by KoenZomers** [comment]
KeePass portable is currently not supported Still need to test this myself to see why it doesn't work.

**Comment by KoenZomers** [comment]
Just gave it a quick try here and it actually works. Can you clarify these points for you:

1. On the system where you face this issue, you don't have KeePass installed at all, only on your memory drive, correct?
2. Under Tools -> OneDrive Sync Options in KeePass, does it show your configured syncs?

**Comment by Ich5003** [comment]
Hey,

answering your questions:
Yes, it only is on my memory drive and it showed the syncs in Options.

But 2.0.2 fixed it, so this issue can be closed.

Thank you 👍

**Comment by KoenZomers** [comment]
Thanks for letting me know @Ich5003! Glad to see it's resolved.
