### ISSUE TITLE
The following plugin is incompatible with the current Keepass version

### ISSUE THREAD

**Issue by xakzona** [KoenZomers/KeePassOneDriveSync#53]
I have installed plugin but received this message on startup
```The following plugin is incompatible with the current Keepass version```
Keepass 2.38

**Comment by KoenZomers** [comment]
Are you using the portable version of KeePass? The plugin doesn't work with that. If you are using the installable version of KeePass ensure you placed the plugin under the plugins subfolder and that it's not blocked. Right click properties at the bottom right check unblock and hit OK. Restart KeePass.
