### ISSUE TITLE
Feature Request: Different remote kdbx credentials from local

### ISSUE THREAD

**Issue by erichiller** [KoenZomers/KeePassOneDriveSync#57]
It would be useful to me, and possibly others to have the remote OneDrive stored kdbx database be keyed differently than the local one. Example use case:
A shared remote database where each user has a local database which is keyed with their windows credentials. All the local databases sync to the single shared remote database which has a static key.

Currently, unless I am mistaken, both the local database and remote must have the same key.

Thanks for the great work!

**Comment by KoenZomers** [comment]
Hi @erichiller,

sounds like it could be useful indeed. This would be something that would need to be implemented on the KeePass side though. I'm using the KeePass API to perform the database merge. My code is only responsible for the communication with the OneDrive services. The actual KeePass functionality under which this would need to be implemented is all in KeePass itself. I recommend you to suggest this feature in the KeePass forum: https://sourceforge.net/p/keepass/discussion/329220/

**Comment by KoenZomers** [comment]
Closing as no further communication is happening
