### ISSUE TITLE
Authentication page never accepts my password. Other methods produre a blank page

### ISSUE THREAD

**Issue by johnarktor** [KoenZomers/KeePassOneDriveSync#58]
Hello,
When I try to sync my database with my OneDrive account, it asks "would you like to set up a configuration", I click yes and there are several options:
- If i chose Microsoft Graph, I get prompted for a login, I enter my OneDrive login, and it never accepts it
- If I chose "Other/Onedrive", it opens a blank page that stays forever blank.

Thank you for your replies, this issue is critical to me and could make me stop using your plugin.

**Comment by KoenZomers** [comment]
Hi @johnarktor,

not sure what's going on here. The pages that are shown where you provide your credentials are coming straight from Microsoft in an Internet Explorer container. So I have no influence over those nor will my code ever be able to touch or verify your credentials. This all happens on the Microsoft side. It could be that it was a temporary glitch in the authentication service. Did you try it again later or from a different network? I've often seen that unstable networks or network security measurements like proxies play a role in this.

**Comment by KoenZomers** [comment]
Closing as no response has been received
