### ISSUE TITLE
Plugin Data not syncing properly

### ISSUE THREAD

**Issue by holygoatnickels** [KoenZomers/KeePassOneDriveSync#59]
There is a problem I noticed with the information under "Database Maintenance > Plugin Data" is getting over written by the server copy.  So if I make changes I have to turn off sync, save the database, upload the new copy and then sync works fine.
Not sure if the sync just checks for entries but this does make it a paint when I make changes to plugin settings.

**Comment by KoenZomers** [comment]
Thanks for reporting this. It's not clear to me what the issue is or why it would not work. I don't encounter this myself and haven't had anyone else report this.

Can you clarify a bit more what you're doing to run into this?

**Comment by KoenZomers** [comment]
Closing as no response has been received
