### ISSUE TITLE
Open database directly from OneDrive

### ISSUE THREAD

**Issue by Kyrodan** [KoenZomers/KeePassOneDriveSync#6]
This item is from your to-do list and I would like to share my opinion.

I like the idea of caching databases offline and I also like opening them in an URL manner. But I also like a convenient way of choosing my file.

I thought on it and came to this concrete conclusion:
We should use WebRequest "Open URL" handler for protocol "onedrive://" (like in IOProtocol extension). With this in mind, the regular KeePass menu commands all work including recent file history. All caching could be done "behind the scene" without the neeed of user interaction (like it's done in KeePass2Android). In the original IOProtocol extension no offline caching is done - it's all kept in memory - but you already have the logic implemented.
You just open it with "Open URL" and everything is done automagically.
This needs some rework of the current workflow, but I think it is much more "KeePass-Native" and no manual file copy and sync-configuration is needed - it's all implicit because of using the onedrive-WebRequest-Handler.

Behind the scenes:
For caching we should use OneDrives file id instead of the path only - like in Keepass2Android. Therefore me need to make sure me do not create a new file for write back of the merged database.

The only thing is the convenient file chooser:
We could add our own "Open OneDrive..." menu item inside "File\Open" menu with a newly created OneDrive file chooser which you already mentioned on your to-do list (samples are in OneDrive SDK and could surely be applied to our scenario). It chooses the file and uses our OneDrive-URL format.

I could work on the first step. After that we could work on the file chooser.
What do you think?

**Comment by Kyrodan** [comment]
I dived more deep into it.

The URI should look like :
>onedrive://\<AccountIdentifier>/\<PathToFile>

The **AccountIdentifier** should be the Accounts' E-Mail-Address. With this in mind we could manage several user readable/identifiable OneDrive accounts and linking several databases to one account. The accounts "credentials" (Drive-ID and Refresh Token) could be stored in the users preferred place (excluding "In the KeePass-Database itself" if opened from OneDrive by URI - this doesn't make any sense in this sepcial case, and in my opinion this should be completely removed because it has too many disadvantages). 

The E-Mail-Address would be the non-editable primary key for a account-table. The Users "Displayname" could additionally be read from Drive's "Owner" item (similar to current behavior). So in any situation where an account should be choosen, you could Display something like *name@myweb.tld (Firstname Lastname)*. I also would like to see the E-Mail-Address as account identifier because with this, we could make an assumption, whether this account is a OneDrive Business (Office 365) account and therefore choose the right API-Base-URL.


Now you can use the current "Open URL" dialog and manually type in your path or you can use our new OneDrive file browser. If you enter the URL by hand and no account could be found, you can now add an account and continue opening the database. 


The file browser could be similar to the regular Open File Dialog with one enhancement: the Account should be selectable from a Combo Box (and adding/managing Accounts could be accessible from this place, too) on above the regular Folder-Tree-Control/FileList. But we could discuss this in detail in another Issue.


This solution is also highly compatible with the current solution (copy by yourself). But maybe we could also discuss on removing this option to take advantage of a much more userfriendly UI and more userfriendly syncing-options.

Opinions?

**Comment by KoenZomers** [comment]
Thanks for your input. I have very little time at the moment to work on this plugin unfortunately. Feel free to fork it and make the modifications you wish. I'll be happy to merge them to the main branch later once you're done.

Is there anything you need from me at this moment to get started?

**Comment by Kyrodan** [comment]
Ok thanks. I don't need anything. I get the plugin compiled and deployed by
myself.

2015-08-21 16:43 GMT+02:00 Koen Zomers <notifications@github.com>:

**Comment by Kyrodan** [comment]
Here are some screenshots from my first "milestone":
# Settings Dialog
![2015-11-03 14_04_02-onedrivesync settings](https://cloud.githubusercontent.com/assets/355178/10908746/3bc7b59a-8234-11e5-9f1a-ca86c5c4310c.png)
![2015-11-03 14_04_18-onedrivesync settings](https://cloud.githubusercontent.com/assets/355178/10908747/3d90044a-8234-11e5-8ecd-da057be8fae7.png)
![2015-11-03 14_04_55-onedrivesync settings](https://cloud.githubusercontent.com/assets/355178/10908749/3ed14c24-8234-11e5-8b00-fabd8722def6.png)


# File Open Dialog

![2015-11-03 14_05_12-keepass](https://cloud.githubusercontent.com/assets/355178/10908751/435090f2-8234-11e5-9f7f-8d220e8a083e.png)
![2015-11-03 14_05_43-open from onedrive](https://cloud.githubusercontent.com/assets/355178/10908752/446b04f4-8234-11e5-9afc-60463f3d5ac7.png)

It's not completed yet, but this is a working basis.
@KoenZomers: Any suggestions?

Regards,
Daniel

**Comment by KoenZomers** [comment]
Awesome! Brilliant work! I’ll give it a try and will get back to you with additional thoughts.

There’s a typo on your general page by the way, “Databasees”

**Comment by KoenZomers** [comment]
I just tried to retrieve your modified code from GitHub without luck. I'm by no means a GitHub expert, so that's probably why. I downloaded your Git fork and in file explorer I do see a subfolder named KoenZomers.KeePass.OneDriveSync in which you made your changes, but if I open the project file it shows me my latest version. How can I get to see your modifications in Visual Studio?

**Comment by Kyrodan** [comment]
You cloned my fork, right? You now have to switch from master branch to the
branch starting "6 - ". In this branch my modifications are done.
Alternativ you can switch to this branch on Github website and download all
as ZIP.
Am 03.11.2015 18:09 schrieb "Koen Zomers" <notifications@github.com>:

**Comment by KoenZomers** [comment]
Got it, thanks :)

**Comment by KoenZomers** [comment]
Just had a look at the code and tried the plugin. Its not clear to me how it is supposed to work. Does this WebRequest.RegisterPrefix registation somehow bind code to using onedrive:/// ? Can't figure out from the code where the actual implementation for this resides. Or is it somehow bound to the OneDrive sync client of Windows itself? I'm not using that client as it doesn't work for me due to the size of my OneDrive. That's why I wrote my own sync client for OneDrive. Does that mean I can't use the plugin anymore?

Also I see you commented out my code to sync with OneDrive. How is the sync supposed to take place? And what would trigger the sync on open and save?

When creating a new database, how can I have it sync with OneDrive? How does adding an extra config entry play a role in this? I don't see any way to connect an entry to a database.

I love the OneDrive picker by the way. Nicely made!

**Comment by Kyrodan** [comment]
Currently syncing/opening is completely disabled. I implemented new
settings with account creation (instead of saving the complete account info
for each database) and the file picker. I also prepared the infrastructure
to use URL-format via WebRequestor for handling onedrive:// links *inside*
KeePass only and compatible to other KeePass features and the regular "Open
URL" UI. I plan to reuse/adapt your sync code (which is currently commented
out) and your OneDrive-library inside the WebRequestor. I do not rely on
Microsofts Windows Client.

So all is good and you will be able to use the plugin like before - just
with some new features, a nice UI and an improved Women Acceptance Factor
:-D
Am 03.11.2015 20:44 schrieb "Koen Zomers" <notifications@github.com>:

**Comment by Kyrodan** [comment]
I implemented Open and Save Operations. Open works as expected *thumbup*, save not *thumbdown*

The problem: 
KeePass does not easily saves the file: it tries to download the recent version, synchonizes it with the current open database, uploads the synced result to a temp file, deletes the original file and then pops up an error (I currently don't know why; I have to dive into KeePass code). The final rename/move call to the temp file is missing. Therefore the Move-Operation in your OneDrive-API is missing; opened an issue for that.

Additionally to that the performance for API calls could be better (maybe streams could be an improvement - currently I have to save content to local temp files).

**Comment by Kyrodan** [comment]
Ok, found my bug ... but could not complete this due to https://github.com/KoenZomers/OneDriveAPI/issues/3:
I need rename and/or move operation in OneDriveApi.

**Comment by Kyrodan** [comment]
I had some problem with KeePass' transacted file writes (which breaks OneDrive history and fills up OneDrives Recycle Bin due to many temp files). See https://sourceforge.net/p/keepass/discussion/329221/thread/d5327367/#af4f.

This is fixed now and tested with a new KeePass developer snapshot (which is uploaded to the repository).

@KoenZomers: Now the complete roundtrip (open/save/update/synchronize) is implemented and could be tested - my works is still not completed and many things need to be polished. The sync part is KeePass' default behavior which I think is very good: it re-downloads the database prior saving, checks for changes, askes the user for sync or overwrite (when needed) and at least uploads the database. If option "Verify Written File After Saving" is enabled (thats the default), then it re-downloads it again and verifies that the dowloaded database is the same as the uploaded one.

Remark:
Automatic offline usage/downloading is still not implemented. After fiddling around I think there are some things to (re-)think about:

What was the initial intent for the way you implemented this plugin? 
* Is it important to have a local copy and another copy in OneDrive?
 * Was the intent "offline usage" and synchronizing it later, when the internet connection is back again?
 * Is it important to specifiy the path to the local copy or could it be hidden to the user?
* What's the "big picture" of this plugin?
 * To have a OneDrive "download helper" and a "sync option on saving"
 * To have a deep integreation in KeePass' infrastructure (which includes synching) and the many functions KeePass provides?

For me a deep integration is important and the offline usage is only nice-to-have. Therefore I do not need a (safe) local copy of my database. Maybe a kind of offline caching could be suggested to be implemented in KeePass' core (because it is an interesting general topic) - like in KeePass2Android.

I'd be glad to hear from you.

Regards,
Daniel
Had some problem with KeePass' transacted file writes (which breaks OneDrive history). See https://sourceforge.net/p/keepass/discussion/329221/thread/d5327367/#af4f.

This is fixed now and tested with a new KeePass developer snapshot (which is uploaded to the repository).

@KoenZomers: Now the complete roundtrip (open/save/update/synchronize) is implemented and could be tested - my works is still not completed and many things need to be polished. The sync part is KeePass' default behavior which I think is very good: it re-downloads the database prior saving, checks for changes, askes the user for sync or overwrite (when needed) and at least uploads the database. If option "Verify Written File After Saving" is enabled (thats the default), then it re-downloads it again and verifies that the dowloaded database is the same as the uploaded one.

Remark:
Automatic offline usage/downloading is still not implemented. After fiddling around I think there are some things to (re-)think about:

What was the initial intent for the way you implemented this plugin? 
* Is it important to have a local copy and another copy in OneDrive?
 * Was the intent "offline usage" and synchronizing it later, when the internet connection is back again?
 * Is it important to specifiy the path to the local copy or could it be hidden to the user?
* What's the "big picture" of this plugin?
 * To have a OneDrive "download helper" and a "sync option on saving"
 * To have a deep integreation in KeePass' infrastructure (which includes synching) and the many functions KeePass provides?

For me a deep integration is important and the offline usage is only nice-to-have. Therefore I do not need a (safe) local copy of my database. Maybe a kind of offline caching could be suggested to be implemented in KeePass' core (because it is an interesting general topic) - like in KeePass2Android.

I'd be glad to hear from you.

Regards,
Daniel

**Comment by KoenZomers** [comment]
Hey Daniel,

didn't get a chance yet to look into this. For me top priority is to have an offline version of the KeePass database as I travel a lot and often am offline while still needing access to the database. Hence the sync once I go online again. So exactly what it does today for 100% matches what I need.

As you might have seen, I have been updating the OneDrive library last night. I tried to incorporate the proxy functionality that I added to it in this KeePass plugin, but I now get a notification that the plugin is incompatible with KeePass. I've had quite a few people report this to me before, but I could never figure out why it gives this error message for some people, but not for others. I managed to dig up the actual error that states that the plugin is created using a newer framework than KeePass is compiled in. That's correct, KeePass is still compiled in old and no longer supported .NET 2.0 and my plugin is compiled against .NET 4.5.2. I can't switch back to .NET 2.0 because of the used code and dependencies and don't want to switch back to an unsupported legacy framework. I just don't understand why it did work before and no longer now while just making relatively minor changes to the code.

Have you seen this behavior before?

Regards,

Koen

**Comment by Kyrodan** [comment]
Ok Koen,

I would like to implement a "transparent" caching mechanism similar to the one in KeePass2Android.
All databases are cached in a caching directory. The data inside is _not_ userfriendly. All is done by the plugin "behind the scenes" depending on online/offline status. You could then open a "onedrive:///" url while being offline, if the database was opened seome time earlier while having been online. Syncing is then done when opening and/or saving a database and the internet connection is back again.
Is this Ok for you?

Your other question should be answered by Dominik Reichel in KeePass Help Forum, right?

Regards,
Daniel

**Comment by KoenZomers** [comment]
To be honest, it sounds like a lot of work and I'm wondering what it would add from what there is at present?

I've had a short look at the Google Drive Sync plugin and that also doesn't support proxies and uses the same kind of sync functionality as the plugin has today already, so why deviate from a proven to satisfy end users method?

**Comment by Kyrodan** [comment]
Before I started developing for this plugin I thought a lot about it and my vision is to help creating the best and ultimate cloud plugin (with OneDrive at first citizen). Thats very optimistic, I know :-) 

I shared my opinion in the first post of this thread. At this point I already checked out technical possibilities and looked at many "sync plugins". What nearly all sync plugins do is to listen to the save event of a local database and do some cloud-magic in background. All this tasks can be done natively with KeePass (or with additional specialized plugins) *if* the URL-Style file location would be implemented. With this in mind many requirements could be satisfied in a better - more KePass native way. But nearly none of the plugin developers did this. The only plugin that that does it "right" IMHO is KeeCloud. The disadvantages of this plugin are the way the cloud API keys are provided and the lack of a good file chooser (both are big big disadvantages for less experienced users). 

So I came to the conclusion that these three points (better, more compatible integration to KeePass, simple file chooser UI and built-in API keys) are the main topics that should be implemented for a deep integration in KeePass and that then other methods (out of the scope of this plugin) could be used to achieve syncing-stuff, doing backups etc.

Therefore KeePass2Android is a very good solution which did all these things very well.

For me, the "proven method" is only a very quick-and-dirty workaround for the main problems. And I already spent a lot of time for reworking this plugin to achieve all the goals and not to only satisfy my personal demand. I have co-workers and friends which do not use KeePass only because of the lack of good and easy to use cloud provider support.

What is present is by the way the method KeePass2Android does caching - this code could be adapted. But after sleeping a night over it I'm unsure this is a task that should be done in our plugin: I think this should be implemented in core KeePass because it is interesting for every user of a (right implemented) storage provider plugin. I would like to request this feature in KeePass forum and wait for some comments. If the conclusion is that this feature would *not* be implemented in KeePass itself, we could implement it in our plugin.

To be fair: this all completely changes the way the plugin currently works - you can even call it a new plugin (with nearly a complete code rewrite).

So what should we do? I think there are two options: I could convince you whith my ideas and inspire you to take a broader look. Or you stay with the current workflow of this plugin. :-)
Please let us find a consense or clearly state that you do not like the way I like to go. If the second is the case then let's talk about alternatives.

What's your opinion?

Regards,
Daniel

**Comment by KoenZomers** [comment]
Thanks for elaborating on your vision. I do appreciate you thinking along on a proper concept for this.

As you probably noticed already, my standpoint is more "selfish" than your vision is: at first I created this plugin because I had a need for it myself. As I noticed there isn't any good plugin for OneDrive available at the moment, I decided to share it. I don't mind spending some time on tweaking it here and there so it will be suitable for other people as well, like in adding proxy support which I don't need myself but got MANY requests for. But my time is limited so I need to spend it wisely.

I like your OneDrive picker as that was something I can imagine will help many people to make this more user friendly. As for the whole setup you're describing above, I feel that would cost too much time and wouldn't solve anything for myself. If it works, it works. I also didn't get any requests from users that would be fulfilled by that approach. I believe it would be better to maybe start your own plugin and implement it there. Which would make more sense as you state that it would be complete rewrite of the code anyway.

I prefer to stick with the sync approach as is in place today as it works well.

**Comment by Kyrodan** [comment]
Ok Koen,

that sounds reasonable and I respect your decision - maybe I would decide the same in your situation. I will think about starting my own plugin with my vision and therefore create a new repository for that. I will keep my forked repository with my development (and therefore the file picker) online for some time. Please feel free to use the filepicker - it should be easy to integrate in your code.

Regards,
Daniel

**Comment by KoenZomers** [comment]
Will do, thanks for your valuable contribution with that!
