### ISSUE TITLE
Plugin remains signed-on to OneDrive

### ISSUE THREAD

**Issue by rangerxusa** [KoenZomers/KeePassOneDriveSync#60]
When signing on to OneDrive to authorize the plugin to access my OneDrive for syncing there is no option checkbox to "remember signon" (or not remember signon). After I authorize and the window closes I find that I am still signed in. I know this because if I authorize another DB the window tells me I am still signed-in.
I see in your code that you do a sign-off before attempting a new sign-in. That code (or the URI you use) appears to not work. For security reasons I think the plugin should always sign-off immediately after an authorization. You do not need to be signed-in to one drive to do a sync once the app is authorized and secrets have been acquired. 
The work around is to delete Internet Explorer cookies/history. Can you check your code and see how to fix this? 
Thanks!

**Comment by KoenZomers** [comment]
Good suggestion to move the signout to directly after obtaining the access and refresh tokens. I'll have a look if I can easily accomplish this.

**Comment by KoenZomers** [comment]
I tried implementing this, but it turns out to be far more complex than I envisioned. Not sure if I will proceed with this as it may introduce a lot of issues and at this moment it doesn't seem to be causing a huge problem for the majority of the users.

**Comment by KoenZomers** [comment]
This issue is also being discussed in https://github.com/KoenZomers/KeePassOneDriveSync/issues/90 along with some options to work around this. Closing this issue to clean up and will continue it there.
