### ISSUE TITLE
Not working with multi factor auth

### ISSUE THREAD

**Issue by tobyw-nasstar** [KoenZomers/KeePassOneDriveSync#61]
We have recently had 2 factor/multifactor authentication enabled for our Office 365 tenant and this plugin no longer works.

**Comment by KoenZomers** [comment]
The plugin supports 2 factor authentication. I think key here is that you set up the sync connection before 2 factor auth was switched on. This typically invalidates all already given out refresh tokens. Try removing the OneDriveSync configuration entry in KeePass, hit ctrl+s again and go through the steps to set up the sync again. It most likely will work again after this.

Please update this thread if this resolved it for you or not.

**Comment by ShonkaiDJ** [comment]
Aha. That may explain why it works. I was surprised to see it login this easy. For Outlook for example, I had to go the Microsoft profile page and get an 'application code'. I expected that to happen with OneDriveSync as well but much to my surprise I could login with just my password and the security code generated by my app.

The other thing other applications will do when you set up two factor authentication is ask if it is a device that you frequently access. OneDriveSync doesn't do that yet stays signed in for days/ weeks usually. I have been thinking if this may become a problem in the future.

the ability to sign in and sign out would be an addition though I cannot remember a situation in which I really needed that. I do remember situations where I thought I'd need it. I just don't remember exactly what situation that was. I may have found a work-around or it wasn't a problem at all.

**Comment by tobyw-nasstar** [comment]
The error I get when trying to configure this is such:

If I click on continue I get a blank page and nothing happens.

This is a fresh install of the plugin

[cid:image001.png@01D3F1C2.6292BE90]


Nasstar for Recruitment
24x7 Support
UK: +44 1604 826 580 
Australia: +61 2831 06952
Singapore: +65 3157 0993
Hong Kong: +85 2580 86468
Rest of the World: +44 1604 826 580 
Toby White
IT Operations Engineer
Nasstar for Recruitment
7 Basset Court, Loake Close, Grange Park, Northampton, Northamptonshire NN4 5EZ, United Kingdom
Email: twhite@nasstar.com
t: +44 1604 826 580
w: recruitment.nasstar.com
Visit our blog - The Nasstarian
Registered in England & Wales, company registration number 04405334. Visit nasstar.com for full details.


Nasstar plc is traded on the London Stock Exchange AIM code: NASA
This message contains confidential information and is intended only for the intended recipients. If you are not an intended recipient you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.

**Comment by KoenZomers** [comment]
@tobyw-nasstar, please open your own issue to troubleshoot this so I can keep things ordered. Thanks!

@ShonkaiDJ, not sure if I can read from your reply that the issue is resolved or not. If not, can you clarify what issue or question still remains?

**Comment by KoenZomers** [comment]
Closing as no response has been received

**Comment by tobyw-nasstar** [comment]
Sorry, I got this all working!

Thanks for your help.


Nasstar for Recruitment
24x7 Support
UK: +44 1604 826 580 
Australia: +61 2831 06952
Singapore: +65 3157 0993
Hong Kong: +85 2580 86468
Rest of the World: +44 1604 826 580 
Toby White
IT Operations Engineer
Nasstar for Recruitment
7 Basset Court, Loake Close, Grange Park, Northampton, Northamptonshire NN4 5EZ, United Kingdom
Email: twhite@nasstar.com
t: +44 1604 826 580
w: recruitment.nasstar.com
Visit our blog - The Nasstarian
Registered in England & Wales, company registration number 04405334. Visit nasstar.com for full details.


Nasstar plc is traded on the London Stock Exchange AIM code: NASA

Recruitment - Please note: All direct applicants that continue to progress their application (with reference to the privacy policy publically available on our website and referenced in the email signatures of all staff) will be deemed to acknowledge and accept our handling of their application in accordance with the provisions set out in our Privacy Policy for Recruitment (https://www.nasstar.com/hubfs/Nasstar-Privacy-Policy-for-Recruitment-Process.pdf). If you have any queries about our privacy policy, please contact HR@Nasstar.com.

This message contains confidential information and is intended only for the intended recipients. If you are not an intended recipient you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.

**Comment by KoenZomers** [comment]
Thanks for confirming @tobyw-nasstar
