### ISSUE TITLE
Account selection not possible

### ISSUE THREAD

**Issue by gweihs** [KoenZomers/KeePassOneDriveSync#63]
Hello!

I tried using KeePassOneDriveSync on two computers and preferred to used my personal OneDrive account over the business one, because the latter kept prompting me for my credentials through the redirection to our corporate authentication. 

Unfortunately, on my laptop with the same OS (Windows 10 PRO 64 bits, but newer build 1803 instead of 1709) the account selection page just flashes for a millisecond and then presents me with the login to my OneDrive business account. From what I can see in the millisecond, it doesn't show the personal account at all. On this problematic computer I have the same Office 2016 Pro and the same setup of MS accounts.

Can I do anything to fix this behavior?

Thanks

Gregor

**Comment by KoenZomers** [comment]
Hi Gregor,

strange behavior. Did you connect through the Graph API option or what did you use?

It doesn't use any Office components, so that plays no role in this. 

What do you see if you use Internet Explorer (MUST be this browser, not any other as the IE container is being used by my plugin) to browse to OneDrive.com? Does it automatically log on for you or do you have to provide your credentials?

**Comment by gweihs** [comment]
Dear Koen,

 

Thank you for your kind reply. Yes, I chose the Graph API. When I browse to onedrive.com with IE I see the standard home page, when I then choose “Login” it prompts me for “E-Mail, Phone or Skype” and I can use either account, same on both computers. 

 

Incidentally, the Domain-member PC now also received the FCU and is on the same build status. I do see a difference, when I go to Settings/App-accounts. There under Microsoft accounts the Domain PC (where the selection works for the plugin) no accounts are listed while on the Laptop (where it doesn’t work) both accounts are listed next to a third that links to Lenovo (no idea why this shows up under Microsoft accounts).

 

Perhaps you can figure something out from this.

 

All the best,

 

Gregor

**Comment by gweihs** [comment]
Hi Koen,

 

just an update, if I choose the OneDrive API from the OneDrive tab in the setup dialog I can enter my user id. I’ll see if this works for me.

 

Best,

 

Gregor

**Comment by KoenZomers** [comment]
Hi @gweihs, any further feedback regarding if you are still encountering issues?

**Comment by gweihs** [comment]
Hi Koen,

 

sorry for not getting back to you earlier. It doesn’t work for me with the Graph API but it worked fine on the OneDrive tab. So all is fine for me.

 

Thanks,

 

Gregor
