### ISSUE TITLE
misspelling in "where to store the onedrive refresh token"

### ISSUE THREAD

**Issue by awesomecogs** [KoenZomers/KeePassOneDriveSync#64]
hi, koen.

in the window "where to store the onedrive refresh token" the word "equivallent" should be spelled "equivalent"

![](https://raw.githubusercontent.com/KoenZomers/KeePassOneDriveSync/master/Screenshots/WhereToStoreOneDriveToken.png)

thanks for a great utility!

**Comment by KoenZomers** [comment]
Thanks for reporting this @awesomecogs! Fixed in version 2.0.2.1.
