### ISSUE TITLE
Database OpenTrigger doesn't start Database Sync.

### ISSUE THREAD

**Issue by andy4711** [KoenZomers/KeePassOneDriveSync#67]
The Database sync isn't started if the database is opened from a Trigger Database Open Action. I assume Trigger Database Close Action behaves similiar.

**Comment by KoenZomers** [comment]
Hi @andy4711. Sorry for the long turnaround time on testing this one. I just set up a test and it works well here. Could be that with the current latest version it was fixed without purposely fixing it, could be that I'm doing something different in my test case than you are.

What I did to try to reproduce it:
1. Created a new Trigger which:
- Activates when copying test to the clipboard in KeePass
- Has no conditions
- Has one action of type "Open database file" specifying the path to a local KeePass database on my file system and providing the password for it
2. I created an entry in my KeePass database which holds the password test
3. I selected this entry in KeePass and hit CTRL+C
4. The plugin triggered and opened the other KeePass database
5. The KeePass database showed in the status bar that it was in sync, thus the plugin did kick in and did do a check if it needed to sync

Not sure if you're still waiting on this to be fixed, but if you are, please let me know if my repro steps are representative and if your'e still facing the issue with the current latest version of the plugin.

**Comment by KoenZomers** [comment]
Have heard from others that this issue should be resolved now, so closing this topic.
