### ISSUE TITLE
Plugin keeps asking for One-drive verification even after token is received.

### ISSUE THREAD

**Issue by N247S** [KoenZomers/KeePassOneDriveSync#69]
As the title says, after you give your One-Drive credentials, the plugin correctly retrieves a token and ask you where to store it. After that I presume it has acces to the One-Drive database if a revisit is required.
But everytime on startup/activation a secondary window pops-up with the message that I logged out of One-Drive (eventhough that shouldn't be necessary anymore after the token has been retrieved).

Its not plugin-breaking, but it becomes quit anoying having to close the secondary window in order to use Keepass normally. Besides for my less-digital colleages it is a point of confusion.

**Comment by KoenZomers** [comment]
@N247S, I understand this is not ideal. This will only happen if it's unable to retrieve an access token based on the refresh token it received from last time. This is likely due to a specific policy enforced on Azure Active Directory which shortens the lifetime of the refresh token from its default. Are you using an Office 365 account or a personal Microsoft Account? Which provider are you using (Graph/OneDrive Consumer/OneDrive for Business)?

**Comment by KoenZomers** [comment]
Are you still having this problem? If yes, can you try the option of not storing it in the Windows Credential Manager? I.e. instead choose the option to store it locally during the sync wizard. See if this makes a difference. Just now on one of my machines I started having a similar like experience which I have never had before. It talks to the Windows API to store the credential manager values, Windows reports back that it did it but in fact it hasn't. Really weird. Choosing to store it locally is a workaround for it here.

**Comment by N247S** [comment]
Sorry that it took a while.
I would love to try this out, but because of [this issue](https://github.com/KoenZomers/KeePassOneDriveSync/issues/82) I am unable test this out.

**Comment by KoenZomers** [comment]
Unfortunately there's nothing I can do to fix this one. See https://github.com/KoenZomers/KeePassOneDriveSync/issues/81#issuecomment-481432362 for more information.

**Comment by N247S** [comment]
Thats unfortunate, but out of your control. The workaround seems to work perfectly
