### ISSUE TITLE
Upload option for database

### ISSUE THREAD

**Issue by awesomecogs** [KoenZomers/KeePassOneDriveSync#74]
Hi, Koen.

As always, thanks much for this great plugin!

I changed my local database's master key and found KeePass OneDriveSync will not sync with the DB in OneDrive anymore (it says composite key is invalid).  In order to successfully sync I had to upload my new KDBX to OneDrive manually.  The plugin "Google Sync Plugin" has the same issue when changing master key but, in addition to a "regular" sync, the plugin provides options for uploading or downloading the database.  After I change my master key I do "Upload to Google Drive" with that plugin before the automatic syncing works again.  It would be helpful to have an upload option in OneDriveSync so I don't have to manually upload.

Thanks again and keep up the great work!

**Comment by KoenZomers** [comment]
That's a nice one. I'll consider adding it.

**Comment by KoenZomers** [comment]
This has been added in version 2.0.7.0. After the dialog showing that the import/merge couldn't complete, you will now get a new dialog which allows you to upload the local database to online overwriting your existing database there. So in the scenario of a changed master password, just let it save and after the error dialog choose yes to upload it to your cloud storage. No more manual steps needed.
