### ISSUE TITLE
Authentication Window Garbled

### ISSUE THREAD

**Issue by projectje** [KoenZomers/KeePassOneDriveSync#77]
https://1drv.ms/u/s!Aqfdr5Dct1YHwSYrZVoyBMKPkWHT

When trying to setup a connection the initial authentication dialog is a bit garbled and it is hard to make out what to click.

**Comment by KoenZomers** [comment]
I don't have any control over the contents of that dialog. That's a website coming from Microsoft. Could it be that you have modified the font size settings in Windows? Or perhaps are using a very high or low resolution screen?
