### ISSUE TITLE
Update check shows pre-release version

### ISSUE THREAD

**Issue by xopez** [KoenZomers/KeePassOneDriveSync#79]
Hello,

I think the image is enough to understand what i mean.
Avaiable version should be the installed one.
![grafik](https://user-images.githubusercontent.com/28950736/51973161-4ba30e80-247d-11e9-81e6-089ea6d8d461.png)

**Comment by KoenZomers** [comment]
Valid point. Must have missed that in my last update. Fixed now. Thanks!
