### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by IanIreland** [KoenZomers/KeePassOneDriveSync#80]
I have been using this plugin for a while but saw the update message so have tried to update.
I have copied the KeeOneDriveSync.plgx into the relevant folder, file dated 1.2.19
When I open KeePass it still shows version 2.0.2.0 and I keep getting the message on startup than an update is available?
I did clear the cache but that didn't help.
I'm sure I have done something wrong but can't see what.
Any advice appreciated.

**Comment by KoenZomers** [comment]
Did you use the PLGX or the DLLs from the Releases page?
https://github.com/KoenZomers/KeePassOneDriveSync/releases

The change from 2.0.2.0 to 2.0.2.1 is minimal, but I can imagine that the notification that an update is available can be irritating.

**Comment by IanIreland** [comment]
Thank for getting back to me. I downloaded the PLGX with the new GitHub desktop and used the PLGX file from there.

**Comment by KoenZomers** [comment]
Works fine for me. Just tried again.

Did you put it in C:\Program Files (x86)\KeePass Password Safe 2\Plugins? Ensure you don't have another version of it in C:\Program Files (x86)\KeePass Password Safe 2 as well. Or are you using the portable KeePass?

**Comment by IanIreland** [comment]
All my programs are on P: so P:\Program Files (x86)\KeePass Password Safe 2\Plugins and a search on the hard drives only finds one copy and it's in that directory. How odd!

**Comment by IanIreland** [comment]
Nope - not blocked! I may try uninstalling and re-installing. Do I simply delete the plgx file?

**Comment by KoenZomers** [comment]
Yes just close KeePass, delete the PLGX, start KeePass, confirm from the Help -> Check for updates dialog that it's gone, close KeePass, throw the PLGX into the Plugins subfolder, restart KeePass and it should show you that it's compiling the PLGX, albeit in just a few seconds.

**Comment by IanIreland** [comment]
There must be a 'wrong' file floating about. I followed the instructions above, including checking I didn't have any plugins showing in KeePass. I then copied the PLGX file from the downloaded repository into the plugins folder.
I opened KeePass, it compiled. I then opened KeePass and it is there but showing as 2.0.2.0.

**Comment by IanIreland** [comment]
That has worked. Thank you very much. I was downloading using the Windows GitHub app. Perhaps there is a problem there.

**Comment by IanIreland** [comment]
We have crossed in the post. I had previously cleared the cache but that didn't help. This time I simply copied (and replaced) the file you sent. When I opened KeePass it compiled and the new version was there.

**Comment by KoenZomers** [comment]
Ah! Mystery solved luckily!
