### ISSUE TITLE
Unable to retrieve acces token

### ISSUE THREAD

**Issue by N247S** [KoenZomers/KeePassOneDriveSync#82]
Goodday,

I tried to solve the issue I posted [here](https://github.com/KoenZomers/KeePassOneDriveSync/issues/69), but I came across this issue.
Any ideas how to passby/fix this?
![image](https://user-images.githubusercontent.com/10078398/55161287-7223b400-5165-11e9-8d1a-c14e4e818fb1.png)

stacktrace:

>  bij KoenZomers.OneDrive.Api.OneDriveApi.<PostToTokenEndPoint>d__51.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij KoenZomers.OneDrive.Api.OneDriveForBusinessO365Api.<GetAccessTokenFromAuthorizationToken>d__14.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij KoenZomers.OneDrive.Api.OneDriveForBusinessO365Api.<GetAccessTokenFromAuthorizationToken>d__17.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij KoenZomers.OneDrive.Api.OneDriveApi.<GetAccessToken>d__49.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij KoenZomersKeePassOneDriveSync.OneDriveAuthenticateForm.<WebBrowser_Navigated>d__0.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

This occures everything I try to add a new configuration (after deleting the old one, in order to activate the credential saving on the pc itself insteadof Windows Credential Manager).

Sometimes the microsoft login screen (which this popup is spawned from) blocks and makes KeePass unusable wihtout reset via taskmanager.

**Comment by KoenZomers** [comment]
Are you using the latest version of the plugin? This issue should have been resolved already. I see you're using the OneDrive for Business option. If you switch to the Microsoft Graph option, the problem should definitely be gone.

**Comment by N247S** [comment]
Updated, and fixed indeed.
