### ISSUE TITLE
Failed to login to OneDrive !?

### ISSUE THREAD

**Issue by mariusZZ51** [KoenZomers/KeePassOneDriveSync#83]
after restarting PC always asking me to login again !! now i even can't login !!!! but is working if I'm doing all steps from the beginning !!! what is the problem here in past everything was alight !!!
![2nd problem](https://user-images.githubusercontent.com/36503666/55719651-a5cccc80-59f6-11e9-9736-cd06be6ff8e3.PNG)

**Comment by KoenZomers** [comment]
This is not a dialog coming forward from my plugin. I think you're using something else. Perhaps the File -> Synchronize option?

**Comment by KoenZomers** [comment]
Closing as no further information has been received and the dialog does not belong to this plugin.
