### ISSUE TITLE
OneDrive keeps asking for authentication

### ISSUE THREAD

**Issue by Olli2k** [KoenZomers/KeePassOneDriveSync#85]
Hi, since updating to 2.0.3.0 I need to do the Onedrive auth at every reboot (just checked, it is every start of KeePass).

**Comment by KoenZomers** [comment]
Where are you storing your Refresh Token? Inside the database or on the file system?

**Comment by Olli2k** [comment]
This option is not given during "restart auth". It is just asking for mail and account type. Finally I have to click "Yes" for auth and that's it. If I remeber correctly I selected Windows cred. manager or something like this at first setup. I will update on another synced system later, and report if there is the same problem.

**Comment by Olli2k** [comment]
Okay, tested update on my second and third PC. Same probblem everywhere, Restart KeePass = New auth on onedrive, with described behauviour.

**Comment by KoenZomers** [comment]
That's correct. You have to delete your config under the KeePass OneDriveSync settings screen and set up the sync again.

**Comment by Olli2k** [comment]
Deleted config and did a reauth. After restarting KeePass I have to auth again. So not my solution.

**Comment by tbar9999** [comment]
I am also having this issue after upgrading to 2.0.3.0. How do you delete the KeePass OneDriveSync settings?

**Comment by KoenZomers** [comment]
> I am also having this issue after upgrading to 2.0.3.0. How do you delete the KeePass OneDriveSync settings?

Tools -> OneDriveSync Options -> click on the line with your config and hit Delete

> Deleted config and did a reauth. After restarting KeePass I have to auth again. So not my solution.

Where did you choose to store the refresh token?

**Comment by Olli2k** [comment]
In database. Not local.

**Comment by KoenZomers** [comment]
> In database. Not local.

Strange. Can you run a Fiddler trace before you start KeePass in which this situation reproduces and e-mail it to me so I can check what's going on under the hood that it doesn't like the refresh token?

**Comment by tbar9999** [comment]
> > I am also having this issue after upgrading to 2.0.3.0. How do you delete the KeePass OneDriveSync settings?
> 
> Tools -> OneDriveSync Options -> click on the line with your config and hit Delete

Thanks! That fixed it for me.

**Comment by broo0ose** [comment]
> > > I am also having this issue after upgrading to 2.0.3.0. How do you delete the KeePass OneDriveSync settings?
> > 
> > 
> > Tools -> OneDriveSync Options -> click on the line with your config and hit Delete
> 
> Thanks! That fixed it for me.

Me too, after upgrade to 2.0.4.0 and KP 2.42.1
thanks for your Plugin and support.

**Comment by KoenZomers** [comment]
@Olli2k to grasp back to your situation as you started this topic, could you try it with v2.0.4.0? I have changed something in it where it would ask for authentication again if using a shared database. Maybe not exactly your scenario but who knows, we may be lucky.

**Comment by KoenZomers** [comment]
Closing this for now as no further input has been received. Feel free to reopen if this issue still persists.
