### ISSUE TITLE
Update Check - KeePass "Release 2.0.3" ?

### ISSUE THREAD

**Issue by lrvl** [KoenZomers/KeePassOneDriveSync#86]
KeePass Update Check message mentions: "New version available!" v2.0.3 but the Releases page doesn't contain the new version?

**Comment by KoenZomers** [comment]
I knew I forgot something :) Thanks for the reminder, I'll create it right-away.

**Comment by KoenZomers** [comment]
Done, thanks again for letting me know.
https://github.com/KoenZomers/KeePassOneDriveSync/releases/tag/2.0.3.0

**Comment by lrvl** [comment]
Thanks for resolving this issue so quickly!
