### ISSUE TITLE
Your PlugIn is determined by Hitman Pro 3.7.9. (build 779) as Malicious Code

### ISSUE THREAD

**Issue by kwhjvdkamp** [KoenZomers/KeePassOneDriveSync#87]
![image](https://user-images.githubusercontent.com/9660415/57100034-3b215f00-6d1e-11e9-9aed-91923d8764a9.png)

Mitigation   Lockdown
Timestamp    2019-05-02T18:51:11

Platform     10.0.17134/x64 v779 06_45
PID          3916
Feature      00171A361FBF01B6
Application  C:\Program Files (x86)\KeePass Password Safe 2\KeePass.exe
Created      2019-05-02T18:06:37
Modified     2019-05-01T10:58:42
Description  KeePass 2.42

Filename     C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe

Command line:
"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe" /noconfig /fullpaths @"C:\Users\***********\AppData\Local\Temp\kamh5zbh.cmdline"

Loaded Modules
-----------------------------------------------------------------------------
0000000000870000-0000000000B9C000 KeePass.exe (Dominik Reichl), 
                                  version: 2.42.0.0
00007FFA140E0000-00007FFA142C1000 ntdll.dll (Microsoft Corporation), 
                                  version: 10.0.17134.228 (WinBuild.160101.0800)
00007FFA13590000-00007FFA13642000 KERNEL32.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FF9FCC30000-00007FF9FCC94000 MSCOREE.DLL (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA106A0000-00007FFA10913000 KERNELBASE.dll (Microsoft Corporation), 
                                  version: 10.0.17134.165 (WinBuild.160101.0800)
00007FFA0FF50000-00007FFA10139000 hmpalert.dll (SurfRight B.V.), 
                                  version: 3.7.9.779
00007FFA130C0000-00007FFA13161000 ADVAPI32.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA139F0000-00007FFA13A8E000 msvcrt.dll (Microsoft Corporation), 
                                  version: 7.0.17134.1 (WinBuild.160101.0800)
00007FFA11BC0000-00007FFA11C1B000 sechost.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA137F0000-00007FFA13914000 RPCRT4.dll (Microsoft Corporation), 
                                  version: 10.0.17134.112 (WinBuild.160101.0800)
00007FF9FC320000-00007FF9FC3BC000 mscoreei.dll (Microsoft Corporation), 
                                  version: 4.7.3056.0 built by: NET472REL1
00007FFA11570000-00007FFA115C1000 SHLWAPI.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA13D50000-00007FFA14073000 combase.dll (Microsoft Corporation), 
                                  version: 10.0.17134.112 (WinBuild.160101.0800)
00007FFA10AC0000-00007FFA10BBA000 ucrtbase.dll (Microsoft Corporation), 
                                  version: 10.0.17134.191 (WinBuild.160101.0800)
00007FFA11470000-00007FFA114EA000 bcryptPrimitives.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA13170000-00007FFA13198000 GDI32.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA10920000-00007FFA10AB2000 gdi32full.dll (Microsoft Corporation), 
                                  version: 10.0.17134.112 (WinBuild.160101.0800)
00007FFA10C10000-00007FFA10CAF000 msvcp_win.dll (Microsoft Corporation), 
                                  version: 10.0.17134.137 (WinBuild.160101.0800)
00007FFA13660000-00007FFA137F0000 USER32.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA114F0000-00007FFA11510000 win32u.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA14080000-00007FFA140AD000 IMM32.DLL (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA10490000-00007FFA104A1000 kernel.appcore.dll (Microsoft Corporation), 
                                  version: 10.0.17134.112 (WinBuild.160101.0800)
00007FF9FCE70000-00007FF9FCE7A000 VERSION.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FF9FB920000-00007FF9FC30C000 clr.dll (Microsoft Corporation), 
                                  version: 4.7.3132.0 built by: NET472REL1LAST
00007FF9FB820000-00007FF9FB917000 MSVCR120_CLR0400.dll (Microsoft Corporation), 
                                  version: 12.00.52519.0 built by: VSWINSERVICING
00007FF9FA0C0000-00007FF9FB648000 mscorlib.ni.dll (Microsoft Corporation), 
                                  version: 4.7.3132.0 built by: NET472REL1LAST
00007FFA131A0000-00007FFA132F1000 ole32.dll (Microsoft Corporation), 
                                  version: 10.0.17134.137 (WinBuild.160101.0800)
00007FFA0E6A0000-00007FFA0E738000 uxtheme.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA10150000-00007FFA10167000 CRYPTSP.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA0F620000-00007FFA0F653000 rsaenh.dll (Microsoft Corporation), 
                                  version: 10.0.17134.191 (WinBuild.160101.0800)
00007FFA0FF20000-00007FFA0FF45000 bcrypt.dll (Microsoft Corporation), 
                                  version: 10.0.17134.112 (WinBuild.160101.0800)
00007FFA0FB90000-00007FFA0FB9B000 CRYPTBASE.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FF9F8EF0000-00007FF9F9B2F000 System.ni.dll (Microsoft Corporation), 
                                  version: 4.7.3151.0 built by: NET472REL1LAST_B
00007FF9B09C0000-00007FF9B13CF000 KeePass.ni.exe (Dominik Reichl), 
                                  version: 2.42.0.0
00007FF9D8460000-00007FF9D8648000 System.Drawing.ni.dll (Microsoft Corporation), 
                                  version: 4.7.3056.0 built by: NET472REL1
00007FF9D02F0000-00007FF9D123D000 System.Windows.Forms.ni.dll (Microsoft Corporation), 
                                  version: 4.7.3056.0 built by: NET472REL1
00007FFA13940000-00007FFA139E9000 ShCore.dll (Microsoft Corporation), 
                                  version: 10.0.17134.112 (WinBuild.160101.0800)
00007FF9F80E0000-00007FF9F8B30000 System.Core.ni.dll (Microsoft Corporation), 
                                  version: 4.7.3160.0 built by: NET472REL1LAST_C
00007FF9F40B0000-00007FF9F41DA000 System.Configuration.ni.dll (Microsoft Corporation), 
                                  version: 4.7.3056.0 built by: NET472REL1
00007FF9ECED0000-00007FF9ED75C000 System.Xml.ni.dll (Microsoft Corporation), 
                                  version: 4.7.3056.0 built by: NET472REL1
00007FFA11C20000-00007FFA13060000 shell32.dll (Microsoft Corporation), 
                                  version: 10.0.17134.228 (WinBuild.160101.0800)
00007FFA10BC0000-00007FFA10C09000 cfgmgr32.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA10D60000-00007FFA1146D000 windows.storage.dll (Microsoft Corporation), 
                                  version: 10.0.17134.228 (WinBuild.160101.0800)
00007FFA10450000-00007FFA1046F000 profapi.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA10400000-00007FFA1044C000 powrprof.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA103F0000-00007FFA103FA000 FLTLIB.DLL (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA00670000-00007FFA008D9000 comctl32.dll (Microsoft Corporation), 
                                  version: 6.10 (WinBuild.160101.0800)
00007FFA0E930000-00007FFA0E959000 dwmapi.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FF9F9B30000-00007FF9F9C5C000 clrjit.dll (Microsoft Corporation), 
                                  version: 4.7.3132.0 built by: NET472REL1LAST
00007FF9FE670000-00007FF9FE67C000 secur32.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA102F0000-00007FFA10320000 SSPICLI.DLL (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FF9FDF30000-00007FF9FDFD7000 comctl32.dll (Microsoft Corporation), 
                                  version: 5.82 (WinBuild.160101.0800)
00007FFA13B70000-00007FFA13CE5000 MSCTF.dll (Microsoft Corporation), 
                                  version: 10.0.17134.191 (WinBuild.160101.0800)
00007FFA13AA0000-00007FFA13B62000 OLEAUT32.dll (Microsoft Corporation), 
                                  version: 10.0.17134.48 (WinBuild.160101.0800)
00007FFA00490000-00007FFA0062A000 gdiplus.dll (Microsoft Corporation), 
                                  version: 10.0.17134.228 (WinBuild.160101.0800)
0000000004220000-000000000453C000 DWrite.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FF9E93D0000-00007FF9E9465000 RichEd20.DLL (Microsoft Corporation), 
                                  version: 5.31.23.1231
00007FF9FF3C0000-00007FF9FF3D9000 USP10.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FF9E9390000-00007FF9E93C8000 msls31.dll (Microsoft Corporation), 
                                  version: 3.10.349.0
00007FFA0BD90000-00007FFA0BF3E000 WindowsCodecs.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA13480000-00007FFA13520000 clbcatq.dll (Microsoft Corporation), 
                                  version: 2001.12.10941.16384 (WinBuild.160101.080
00007FF9D2CE0000-00007FF9D2D38000 dataexchange.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA0D530000-00007FFA0D83B000 d3d11.dll (Microsoft Corporation), 
                                  version: 10.0.17134.112 (WinBuild.160101.0800)
00007FFA0DE40000-00007FFA0DFDC000 dcomp.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA0EF80000-00007FFA0F03B000 dxgi.dll (Microsoft Corporation), 
                                  version: 10.0.17134.112 (WinBuild.160101.0800)
00007FFA0EAC0000-00007FFA0EC78000 twinapi.appcore.dll (Microsoft Corporation), 
                                  version: 10.0.17134.137 (WinBuild.160101.0800)
00007FFA0EA10000-00007FFA0EA31000 RMCLIENT.dll (Microsoft Corporation), 
                                  version: 10.0.17134.81 (WinBuild.160101.0800)
00007FF9E8120000-00007FF9E81C5000 tiptsf.dll (Microsoft Corporation), 
                                  version: 10.0.17134.191 (WinBuild.160101.0800)
00007FFA03710000-00007FFA037A7000 TextInputFramework.dll (Microsoft Corporation), 
                                  version: 10.0.17134.191 (WinBuild.160101.0800)
00007FFA0B890000-00007FFA0BBAE000 CoreUIComponents.dll (Microsoft Corporation), 
                                  version: 10.0.17134.112
00007FFA0DFE0000-00007FFA0E0BA000 CoreMessaging.dll (Microsoft Corporation), 
                                  version: 10.0.17134.228
00007FFA0F2B0000-00007FFA0F2E1000 ntmarta.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA0C120000-00007FFA0C26D000 wintypes.dll (Microsoft Corporation), 
                                  version: 10.0.17134.112 (WinBuild.160101.0800)
00007FFA0CC30000-00007FFA0CC43000 wtsapi32.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA0F320000-00007FFA0F376000 WINSTA.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA0FC10000-00007FFA0FC24000 wldp.dll (Microsoft Corporation), 
                                  version: 10.0.17134.228 (WinBuild.160101.0800)
00007FFA104B0000-00007FFA10692000 CRYPT32.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA10470000-00007FFA10482000 MSASN1.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)
00007FFA11510000-00007FFA11567000 WINTRUST.dll (Microsoft Corporation), 
                                  version: 10.0.17134.81 (WinBuild.160101.0800)
00007FFA10320000-00007FFA10348000 USERENV.dll (Microsoft Corporation), 
                                  version: 10.0.17134.1 (WinBuild.160101.0800)

Process Trace
1  C:\Program Files (x86)\KeePass Password Safe 2\KeePass.exe [3916] 2019-05-02T18:51:08
2  C:\WINDOWS\explorer.exe [8660] 2019-05-01T11:14:31
3  C:\WINDOWS\System32\userinit.exe [8432] 2019-05-01T11:14:30 33.9s

Thumbprint
f95e9b51bd5d76517aa275980423fb8d70f85b4f3c3043612d9f931080b59ce5

**Comment by KoenZomers** [comment]
That's odd. Wouldn't know what's malicious about it. Also don't see how the issue relates to the plugin from what you're sharing? Or am I overlooking something? If you delete the plugin and just start KeePass, it doesn't detect it as malicious?

**Comment by kwhjvdkamp** [comment]
Hi Koen,

No! Without your plugin installed, KeePass (latest 2.42) starts normally. I tried the other plugin from Daniel Bölts (KeeAnywhere). 

He mentioned, he is inspired by your brain waves, how does that sound to you, nice is n‘t it? 

Actually, Daniels’ plugin worked right away, no trouble. Oké, I’ll be honest, I’ve tried that one my desktop, your plugin was on my LT. 

Tonight, I’ll install Daniels’ plugin on my LT too, see what happens. I’ll let you know..

 

Regards, 

Koen

 

Van: Koen Zomers <notifications@github.com> 
Verzonden: vrijdag 3 mei 2019 12:58
Aan: KoenZomers/KeePassOneDriveSync <KeePassOneDriveSync@noreply.github.com>
CC: kwhjvdkamp <info@van-der-kamp.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [KoenZomers/KeePassOneDriveSync] Your PlugIn is determined by Hitman Pro 3.7.9. (build 779) as Malicious Code (#87)

 

That's odd. Wouldn't know what's malicious about it. Also don't see how the issue relates to the plugin from what you're sharing? Or am I overlooking something? If you delete the plugin and just start KeePass, it doesn't detect it as malicious?

**Comment by KoenZomers** [comment]
Yes, Daniel and myself have been in contact in the past on the development of the KeePass plugin but our ideas on it were a bit too far away from each other and that's why he started his own plugin for KeePass.

I have contacted Hitman Pro support to inquire what it would be that would be triggering it as malware. Did you recently update KeePass and/or the plugin that could be causing it to be flagged? Or is it a new installation? I don't use Hitman Pro myself, so I can't validate it from my end.

**Comment by kwhjvdkamp** [comment]
KeePass 2.42 (latest, two days ago I presume), also Hitman Pro latest version.

 

With regards,

Koen

 

Van: Koen Zomers <notifications@github.com> 
Verzonden: vrijdag 3 mei 2019 19:15
Aan: KoenZomers/KeePassOneDriveSync <KeePassOneDriveSync@noreply.github.com>
CC: kwhjvdkamp <info@van-der-kamp.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [KoenZomers/KeePassOneDriveSync] Your PlugIn is determined by Hitman Pro 3.7.9. (build 779) as Malicious Code (#87)

 

Yes, Daniel and myself have been in contact in the past on the development of the KeePass plugin but our ideas on it were a bit too far away from each other and that's why he started his own plugin for KeePass.

I have contacted Hitman Pro support to inquire what it would be that would be triggering it as malware. Did you recently update KeePass and/or the plugin that could be causing it to be flagged? Or is it a new installation? I don't use Hitman Pro myself, so I can't validate it from my end.

**Comment by KoenZomers** [comment]
Did it get flagged as malware with previous versions already or only after you updated the plugin and/or KeePass? What did you do when it started reporting it?

**Comment by kwhjvdkamp** [comment]
Hi Koen, 

As said, two days ago I updated KeePass according the push message a
newest version available 2.42. 

Yesterday evening I decided (finally) to use a plugin to synchronize
keepass databases (actually I finally I had the guts to upload a keepass
database to OneDrive). 

So, I never had a plugin installed in my KeePass environment before. 

As said, Hitman Pro on my LT detected your tool as malicious. 

Therefore, sorry for you, I decided to try another plugin and choose the
Daniels' thing and installed that on my desktop today. 

That went very straight forward. Now, I'm busy on my LT again, as
promised, I installed Daniels' (Jack) as well... Actually, again with
Jack Daniels', on my LT as well: No, nol troubles!  

What I exactly did yesterday: 

1) downloaded your plugin form, 

2) cut it from the download folder, 

3) stored it in folder ~\Program Files (x86)\KeePass Password Safe
2\Plugins\ telling the system I did have administrator rights to store
it, 

4) hit the KeePass alias on my task bar: keepass opened, showing
something about a plugin loading and whoala boem the screen warning I've
send you, 

5) cancelled, 

6) downloaded it again, 

7) cut & pasted it again, again passing by the administrator warning, 

8) reopened Keepass, 

9) noticed again some progress about loading the plugin and within a
second: again the malicious warning screen from Hitman Pro. 

At that moment I decided to submit it as an issue. 

Hopefully it helps, with regards, 

Koen 

Koen Zomers schreef op 03-05-2019 19:23:

> Did it get flagged as malware with previous versions already or only after you updated the plugin and/or KeePass? What did you do when it started reporting it? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/KoenZomers/KeePassOneDriveSync/issues/87#issuecomment-489174224
[2]

**Comment by KoenZomers** [comment]
Thanks for your detailed clarification and letting me know about this. No apologies needed, use whatever works best for you. I'll see if Hitman can provide me with more details on why it's getting flagged and if there will be more users reporting this. So far you're the only one.

**Comment by KoenZomers** [comment]
HitMan Pro support has replied back that the detection was due to their ruleset going haywire and incorrectly marking code as malicious code. It should be resolved now. Their response:

![image](https://user-images.githubusercontent.com/5940670/57223558-c80e3600-7006-11e9-98a1-ce62f0d754c0.png)

**Comment by KoenZomers** [comment]
Another official communication from Hitman Pro on the notification being a false positive and more technical background why it was detected can be found here:

https://www.wilderssecurity.com/threads/hitmanpro-alert-beta.394398/page-61#post-2825802
