### ISSUE TITLE
KeePassOneDriveSync caused System.Net.Sockets.SocketException (0x80004005):

### ISSUE THREAD

**Issue by lijuncq** [KoenZomers/KeePassOneDriveSync#9]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.Net.Sockets.SocketException (0x80004005): 远程主机强迫关闭了一个现有的连接。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    程序集版本:2.30.0.15916
    Win32 版本:2.30.0.0
    基本代码:file:///D:/PortableApp/PortableApps/KeePass2Portable/KeePass.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
KoenZomersKeePassOneDriveSync
    程序集版本:1.3.3.1
    Win32 版本:1.3.3.1
    基本代码:file:///C:/Users/lijun/AppData/Local/KeePass/PluginCache/feXsTTBK3YjWnapjFROG/KoenZomersKeePassOneDriveSync.dll
----------------------------------------
Newtonsoft.Json
    程序集版本:6.0.0.0
    Win32 版本:6.0.8.18111
    基本代码:file:///C:/Users/lijun/AppData/Local/KeePass/PluginCache/feXsTTBK3YjWnapjFROG/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
CredentialManagement
    程序集版本:1.0.2.0
    Win32 版本:1.0.2
    基本代码:file:///C:/Users/lijun/AppData/Local/KeePass/PluginCache/feXsTTBK3YjWnapjFROG/CredentialManagement.DLL
----------------------------------------
KeePass.XmlSerializers
    程序集版本:2.30.0.15916
    Win32 版本:2.30.0.15916
    基本代码:file:///D:/PortableApp/PortableApps/KeePass2Portable/KeePass.XmlSerializers.DLL
----------------------------------------
System.Security
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
KoenZomers.OneDrive.Api
    程序集版本:1.3.1.0
    Win32 版本:1.3.1.0
    基本代码:file:///C:/Users/lijun/AppData/Local/KeePass/PluginCache/feXsTTBK3YjWnapjFROG/KoenZomers.OneDrive.Api.DLL
----------------------------------------
System.Net.Http
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.resources
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

**Comment by KoenZomers** [comment]
Hi Jun,

can you please follow the steps outlined at:

https://github.com/KoenZomers/KeePassOneDriveSync/blob/master/Troubleshooting.md

Thanks!

Koen
