### ISSUE TITLE
OneDrive does not allow me to specify account

### ISSUE THREAD

**Issue by drujd** [KoenZomers/KeePassOneDriveSync#90]
I have two KeePass databases, Personal and Work. One is synced with OneDrive Personal, one with Business. After upgrade to 2.0.4, I was forced do delete sync configuration due to 'remote path is invalid' error. However, now I am unable to select the personal account, the account selection dialog shows only for ~0.5 s and then the Business account is automatically selected.

This problem is not caused by any change in your plugin, I have downgraded to 2.0.3 and 2.0.2.5 and all versions have the same problem, so this is probably caused by changes in OneDrive itself, but I wonder whether there is something to fix that on the plugin side...

**Comment by drujd** [comment]
I am obviously talking about the Graph API.

**Comment by KoenZomers** [comment]
I've seen this before. The plugin uses the Internet Explorer container. If you ever selected automatically logon and "Don't ask me again", it will do so. Also for this plugin as they log in through the same page. Try using Internet Explorer to log on to your OneDrive for Business site and explicitly log out from there. Close Internet Explorer and try it again in KeePass.

Let me know if this works for you.

**Comment by gpion** [comment]
I'm facing the exact same issue and the workaround (disconnect from Onedrive account using IE) did'nt worked.
After having logged out from the Onedrive "pro" account  using IE, I deleted the sync configuration of the personal database,  restarted Keepass, activated Onedrive Sync setup for that database and the pro account is still automatically selected for and pre-authentified (I'm storing Onedrive Credentials on my local computer)

**Comment by ColinCampbellCCL** [comment]
I've just upgraded as well, and have the same issue. It's automatically choosing my work OneDrive sign-in so failing to find the sync file in my personal OneDrive.

I've signed out of OneDrive in IE (which was cached to my work account), but the issue persists. I've even signed in to OneDrive in IE with my personal account, but KeePass still tries to sync with the work account.

**Comment by drujd** [comment]
I have fixed this in (Windows 10) Settings/Accounts/Email & accounts. I have removed all accounts there and then entered the credentials in KeePass OneDrive sync dialogs. Now I see both accounts in Email & accounts. Maybe all you have to do is to make sure both accounts are added there (without removing any accounts).

**Comment by ColinCampbellCCL** [comment]
The solution for me was to set up the personal account sync as "Other > OneDrive" rather than Microsoft Graph, as follows:

1. Open the personal kdbx file.
2. Click Tools > OneDriveSync Options.
3. Select the personal kdbx file, which showed Storage Provider = Microsoft Graph.
4. Right-click > Delete (This will NOT delete the actual KeePass database file, just its configuration for the KeeOneDriveSync plugin) > Yes.
5. Click Close.
6. Close the personal kdbx file.

7. Open the personal kdbx file again. You will be prompted to start syncing with OneDrive.
8. Select Yes and then click OK.
9. Click the Other tab, and then click OneDrive.
Now you will get the "Authenticate to OneDrive" dialog where you can sign in to your preferred account, and then proceed from there.

Choosing "Microsoft Graph (OneDrive & OneDrive for Business)" from the OneDrive tab automatically chooses my corporate account. So it seems that the Microsoft Graph settings only allows one account, and it is cached somehow.

Cheers
Colin

**Comment by ColinCampbellCCL** [comment]
> I have fixed this in (Windows 10) Settings/Accounts/Email & accounts. I have removed all accounts there and then entered the credentials in KeePass OneDrive sync dialogs. Now I see both accounts in Email & accounts. Maybe all you have to do is to make sure both accounts are added there (without removing any accounts).

I already have both my "work or school account" (corporate) and "microsoft account" (personal) accounts listed there; the problem is with OneDriveSync choosing between them. I wouldn't delete accounts from there as it could break lots of other authentication and synchronization on your computer.

**Comment by gpion** [comment]
> The solution for me was to set up the personal account sync as "Other > OneDrive" rather than Microsoft Graph, as follows:

That what I've done too.

**Comment by KoenZomers** [comment]
Good information guys. Let me try to reproduce this scenario so I can hopefully come up with a fix for it.

**Comment by ColinCampbellCCL** [comment]
Thanks. Happy to test for you.

**Comment by ReneHezser** [comment]
> 
> 
> I've seen this before. The plugin uses the Internet Explorer container. If you ever selected automatically logon and "Don't ask me again", it will do so. Also for this plugin as they log in through the same page. Try using Internet Explorer to log on to your OneDrive for Business site and explicitly log out from there. Close Internet Explorer and try it again in KeePass.
> 
> Let me know if this works for you.

It does. Thank you.

**Comment by arcmps** [comment]
I was able to get the login screen to show again by following these steps:

Go to Settings >Your Email & app account settings

Click on the account listed under 'accounts used by other apps' and click 'manage'

Click 'sign out everywhere'

Reopen KeePass and you will be prompted to log into One Drive

![image](https://user-images.githubusercontent.com/35542345/59123949-4d8d4a80-8913-11e9-83b9-1fd23e5fd706.png)

**Comment by KoenZomers** [comment]
Is anyone here still struggling with this issue despite the several options having been mentioned to make it work? I've checked what I can do from a code angle and I can't really find a good solution. There doesn't seem to be a way to open an InPrivate Internet Explorer container. And even if there would be, it would fix your scenario but for many others it would make it less preferable as they wouldn't be able to use their stored accounts without having to log on again. I could try switching to an Edge container, but that will only work on Windows 10 with the April 2018 update or a later version. So it would create split code to support older platforms and it's not even sure that it will fix it.

The login behavior is simply how the service has been designed, I can't change that.

If anyone here has any other ideas how this could be fixed, I'm open for suggestions.

**Comment by ColinCampbellCCL** [comment]
It's working well for me.

I agree it would be a bad idea to try to use an InPrivate session. Being able to choose "Other > OneDrive" is perfectly fine.

There are limitations on access to cloud services. I don't expect app developers to be able to bypass those, but I do expect them to implement the options that are available, as you have done. Thanks.

**Comment by drujd** [comment]
I managed to get it working by adding both personal and work account to Email & accounts in Windows. Closing the issue.
