### ISSUE TITLE
Customize "Storage Name"

### ISSUE THREAD

**Issue by gpion** [KoenZomers/KeePassOneDriveSync#91]
Hello,
I've have two Onedrive accounts, pro and personal.
Both are displayed using the same Storage Name: <Firstname> <Lastname>
Would be nice to be able to configure this.

**Comment by KoenZomers** [comment]
Good suggestion. It already crossed my mind a few times. I'll consider adding an option for it.

**Comment by KoenZomers** [comment]
Added in [version 2.0.4.2](https://github.com/KoenZomers/KeePassOneDriveSync/releases/tag/2.0.4.2)
