### ISSUE TITLE
"Start syncing" dialog should display the database name

### ISSUE THREAD

**Issue by gpion** [KoenZomers/KeePassOneDriveSync#93]
The _"Start syncing with OneDrive"_ dialog do not display the name of the database.
It could be useful at times (when multiple DB are opened in background by a trigger action for instance)
![TAwGIO899x](https://user-images.githubusercontent.com/2971216/58000194-5a6b0b00-7ad8-11e9-9a56-ea08010299f7.png)

**Comment by KoenZomers** [comment]
Added in [version 2.0.4.2](https://github.com/KoenZomers/KeePassOneDriveSync/releases/tag/2.0.4.2)
