### ISSUE TITLE
Sync not working - Upload Error

### ISSUE THREAD

**Issue by WillNottell** [KoenZomers/KeePassOneDriveSync#94]
Hi,

since recently I'm getting the following message when trying to sync my database to my personal OneDrive (note: I'm running on a German Windows 10 but have set the KeePass language to english - parts of the error are in German, though). 

Failed to sync database: Der Wert darf nicht NULL sein.
Parametername: oneDriveUploadSession

I'm using the Microsoft Authenticator App for manually accessing my personal OneDrive in the browser. Could this be an issue?

Syncing has been working flawlessly for years and I cannot tell exactly when syncing began being a problem (the first time I recognized something was different was when I installed the version of the plugin, that prompted for authentication everytime the database was opened, but possibly it started being a problem earlier when I changed the login to use Microsoft Authenticator app. However there wasn't a visible error or something until now with version 2.0.4.1).

It would be nice if someone could point me in the right direction to put things up again.

Thanks, Frank

**Comment by KoenZomers** [comment]
Hi @WillNottell. This has already been reported and I've already created a fix for it. Please check https://github.com/KoenZomers/KeePassOneDriveSync/issues/88 for updates on this to keep it centralized.
