### ISSUE TITLE
Unable to logon on to OneDrive For Business

### ISSUE THREAD

**Issue by rolandraijmakers** [KoenZomers/KeePassOneDriveSync#95]
I use a OneDriveforBusinessAccount to synchronise. But since one week I'm not able toe setup / reset synchronisation to KeeOneDriveSync

I once tried to log in with my Personal account, and now the MsGraph account seems te get stuck to this account, I can not switch to OneDriveForBusiness Account

If I go to the Other tab, and choose for OneDrive for Business I can choose another account, my business Account, but the screen for entering the password is blank, 

I installed the latest version  2.0.6.0 of KeeOneDriveSync.plgx.
I cleared all windows credentials
Under Tools -- Database maintenance -- I cleared plugindata
I shutdown KeePass. In KeePassConfig.xml I deleted the section under Plugindata.

**Comment by KoenZomers** [comment]
Sounds like the same issue reported already in another topic. Can you [try these steps](https://github.com/KoenZomers/KeePassOneDriveSync/issues/90#issuecomment-493585036) and see if this resolves it for you as well?

**Comment by rolandraijmakers** [comment]
@KoenZomers I logged in and out through Internet Explorer with al my three accounts  (one Personal, one User Business and one Admin Account for Business). What I noticed is that after I log in to OneDrive for Business, I can enter a useraccount, but in de following screen where the password dialog should appear, this screen is blank. 
I also think that out setup between our Office for Business accounts and our On premise AD server is a reason why have these problems. Where now using federation services to log in. So My userid is sent to Azure, and my password is verified on te fly on our on premise AD server.

This is going to be changed so that Azure ADFS is going to be setup as a Synchronisation service with our On Premise AD server. 

For now no further action, but leave this post open.

**Comment by KoenZomers** [comment]
That explains it then. What you could do, if they haven't locked down your machine with group policies, is this:

1. Go into the Internet options of Internet Explorer
2. Go to the Security tab
3. Click through the 4 zones displayed and click on the Sites button. Try to figure out to which zone they have added your ADFS server. Likely Local intranet or Trusted sites.
4. Click on the zone in which the ADFS server is listed and click on Custom Level at the bottom
5. Scroll all the way to the bottom to User authentication \ Logon and select Prompt for user name and password
6. Close all dialog boxes, close Internet Explorer and try it again in KeePass. It should not automatically log you on anymore

Fair chance though that the admins have blocked some of these settings for you.

**Comment by rolandraijmakers** [comment]
I don't know what happend, but now it works perfectly.
