### ISSUE TITLE
Authentication fails (OneDrive for Business, ADFS redirection)

### ISSUE THREAD

**Issue by Bogus11** [KoenZomers/KeePassOneDriveSync#98]
Hi Koen,

authentication with OneDrive for Business using Graph API fails: login is being redirected to the ADFS server of our company, and instead of a login page, all I get ist an empty white page.

Latest plugin version, and of course the ADFS authentication works in any other scenario. Is there any way to provide an existing OAuth token instead?

**Comment by KoenZomers** [comment]
Hi @Bogus11, strange. Not without hacking it into the config file yourself. The plugin just uses the Internet Explorer container. Have you tried going to your site specifically with Internet Explorer to see if that works well, so not using any other kind of browser?

**Comment by Bogus11** [comment]
Hi Koen, 
I did a test with IE as recommended by you (in fact never tried this one ever beforer - any other browser but IE :), which was successful. Then I tried the plugin with anoter OfB account which isn't federated, so there's no redirection, just authentication with a native AAD account. This time, the plugin worked without any issues, so it really seems to be about the ADFS redirection. Do you've got any idea about how to troubleshoot this? Is there any log file or other means of getting information what exactly happens when the authentication process is being redirected to our ADFS server and an empty white page is being displayed? Thanks.

**Comment by KoenZomers** [comment]
@Bogus11 your best friend in this scenario is using Fiddler (http://www.fiddler2.com). Enable HTTPS interception and let it capture your traffic while you try to log on through KeePass and through normal use of Internet Explorer. You should see differences.

**Comment by Bogus11** [comment]
Hi @KoenZomers, if the plugin has no other means of having a look under the hood, this will indeed be the method of choice. Thanks for caring and for your fast responses, by the way. However, I was able to sucessfully connect to OfB with the federated account and graph API and get an oauth2 token with other apps (Duplicati for example). So I'm really curious what the issue will turn out to be with your plugin.

**Comment by KoenZomers** [comment]
Me too. There's no further logging being done by my plugin. Deliberate choice for now. Putting logging in something as sensitive as a password database is too risky for leaking or revealing details. If you don't put the details in the logging, the logging would be useless. Retention on the logs would also be a challenge. The long nasty stacktrace error that gets smashed in your face if something goes wrong typically is enough for me to get an idea of what's going on already and doesn't leave a trace on the system after closing it.

**Comment by Bogus11** [comment]
Well, thanks again. If you put it like that, refraining from generating log files seems to be the most sensible decision :) Before fiddling with fiddler, I'm going to have a word with our ADFS guys. Maybe they can find some differences between native IE and the plugin in their logs.

**Comment by KoenZomers** [comment]
Any updates from your side on this @Bogus11?

**Comment by KoenZomers** [comment]
Closing due to no response received
